2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/Master_Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Master Checklist Item</label>
    <nameField>
        <displayFormat>MCI-{0000}</displayFormat>
        <label>Master Checklist Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Checklist Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>Header</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VISITOR ENTRANCE AREA / LOADING AREA</fullName>
            </value>
            <value>
                <fullName>INTERIOR AREA</fullName>
            </value>
            <value>
                <fullName>RECEPTION AREA / VIEWING ROOMS</fullName>
            </value>
            <value>
                <fullName>TRANSIT AREA</fullName>
            </value>
            <value>
                <fullName>RECEIVING/ RELEASING AREA</fullName>
            </value>
            <value>
                <fullName>VISUAL CHECK AREA（AREA DESIGNATED FOR THE DAY)</fullName>
            </value>
            <value>
                <fullName>TOOL AREA</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT AREA</fullName>
            </value>
            <value>
                <fullName>MATERIAL AREA</fullName>
            </value>
            <value>
                <fullName>CARTON WORKSHOP AREA</fullName>
            </value>
            <value>
                <fullName>STORAGE AREA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <externalId>true</externalId>
    <label>Sequence No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Detail__c/Warehouse_Detail__c.object-meta.xml
<CustomObject>
    <label>Warehouse Detail</label>
    <nameField>
        <label>Warehouse Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/WareHouseChecklistTest.cls
@isTest 
private class WareHouseChecklistTest {
    @testSetup static void methodName() {
        Master_Checklist_Item__c mci = new Master_Checklist_Item__c();
        mci.Header__c='Test Header';
        mci.Item__c='Question?';
        mci.Sequence_No__c=10;
        mci.IsActive__c=True;
        insert mci;
        
        Warehouse_Detail__c wd = new Warehouse_Detail__c();
        wd.Name='WareHouse Test';
        insert wd;
        
    }
    
    static testMethod void validateAttachment(){
        test.startTest();
        List<Master_Checklist_Item__c> chckItem = [Select Id from Master_Checklist_Item__c where IsActive__c=True];
        List<Warehouse_Detail__c> wdetail = [Select Id from Warehouse_Detail__c where Name='WareHouse Test'];
        WareHouseChecklist.fetchChecklistItems();
        String json = '[{"id":"'+chckItem[0].id+'","picklist":"Yes","remarks": "Test Remarks"}]';
        WareHouseChecklist.saveRec(json,wdetail[0].Id,'Test User');
        test.stopTest();
    }
}