2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/Master_Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Master Checklist Item</label>
    <nameField>
        <displayFormat>MCI-{0000}</displayFormat>
        <label>Master Checklist Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Checklist Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>Header</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VISITOR ENTRANCE AREA / LOADING AREA</fullName>
            </value>
            <value>
                <fullName>INTERIOR AREA</fullName>
            </value>
            <value>
                <fullName>RECEPTION AREA / VIEWING ROOMS</fullName>
            </value>
            <value>
                <fullName>TRANSIT AREA</fullName>
            </value>
            <value>
                <fullName>RECEIVING/ RELEASING AREA</fullName>
            </value>
            <value>
                <fullName>VISUAL CHECK AREA（AREA DESIGNATED FOR THE DAY)</fullName>
            </value>
            <value>
                <fullName>TOOL AREA</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT AREA</fullName>
            </value>
            <value>
                <fullName>MATERIAL AREA</fullName>
            </value>
            <value>
                <fullName>CARTON WORKSHOP AREA</fullName>
            </value>
            <value>
                <fullName>STORAGE AREA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <externalId>true</externalId>
    <label>Sequence No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <label>Warehouse Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_Location</valueSetName>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_CheckList__c/Warehouse_Daily_CheckList__c.object-meta.xml
<CustomObject>
    <label>Warehouse Daily CheckList</label>
    <nameField>
        <displayFormat>WDC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warehouse Daily CheckLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_CheckList__c/fields/Inspected_By__c.field-meta.xml
<CustomField>
    <fullName>Inspected_By__c</fullName>
    <label>Inspected By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_CheckList__c/fields/Inspection_Date__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Date__c</fullName>
    <label>Inspection Date</label>
    <type>DateTime</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_CheckList__c/fields/Warehouse_Detail__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Detail__c</fullName>
    <label>Warehouse Detail</label>
    <referenceTo>Warehouse_Detail__c</referenceTo>
    <relationshipLabel>Warehouse Daily CheckLists</relationshipLabel>
    <relationshipName>Warehouse_Daily_CheckLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_Checklist_Item__c/Warehouse_Daily_Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Warehouse Daily Checklist Item</label>
    <nameField>
        <displayFormat>WDCI-{0000}</displayFormat>
        <label>Warehouse Daily Checklist Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Warehouse Daily Checklist Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_Checklist_Item__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_Checklist_Item__c/fields/Master_Checklist_Item__c.field-meta.xml
<CustomField>
    <fullName>Master_Checklist_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Checklist Item</label>
    <referenceTo>Master_Checklist_Item__c</referenceTo>
    <relationshipLabel>Warehouse Daily Checklist Items</relationshipLabel>
    <relationshipName>Warehouse_Daily_Checklist_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_Checklist_Item__c/fields/Points_Areas_to_be_checked__c.field-meta.xml
<CustomField>
    <fullName>Points_Areas_to_be_checked__c</fullName>
    <label>Points/Areas to be checked</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_Checklist_Item__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Daily_Checklist_Item__c/fields/Warehouse_Daily_CheckList__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Daily_CheckList__c</fullName>
    <label>Warehouse Daily CheckList</label>
    <referenceTo>Warehouse_Daily_CheckList__c</referenceTo>
    <relationshipLabel>Warehouse Daily Checklist Items</relationshipLabel>
    <relationshipName>Warehouse_Daily_Checklist_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Detail__c/Warehouse_Detail__c.object-meta.xml
<CustomObject>
    <label>Warehouse Detail</label>
    <nameField>
        <label>Warehouse Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Detail__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <description>Warehouse Location</description>
    <label>Warehouse Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_Location</valueSetName>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/globalValueSets/Warehouse_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Singapore</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <masterLabel>Warehouse Location</masterLabel>
</GlobalValueSet>

Arpan-PersonalOrg/force-app/main/default/classes/WareHouseChecklist.cls
/**
* Author: Nitin
* CreatedDate: 19/04/2021
* Description: Below apex code is used to retrieve the Checklist Questions & Save the responses for the corresponding questions
**/ 

public class WareHouseChecklist {
    
    @AuraEnabled
    public static List<Master_Checklist_Item__c> fetchChecklistItems(String wareHouseLoc){
        List<Master_Checklist_Item__c> chckItem = [Select Id,Header__c,Item__c,Sequence_No__c,Mandatory__c,Warehouse_Location__c from Master_Checklist_Item__c where IsActive__c=True and Warehouse_Location__c includes (:wareHouseLoc) ORDER BY Sequence_No__c ASC];
        return chckItem;
    }
    @AuraEnabled
    public static String saveRec(String masterAnswers,String WarehouseDetails,String InspectedBy,String frequencyPicklist){
        String recordId;
        try{
            if(String.isNotBlank(masterAnswers)){
                Map<Id,Master_Checklist_Item__c> ChecklistItemMap = new Map<Id,Master_Checklist_Item__c>([Select Id,Header__c,Item__c,Sequence_No__c from Master_Checklist_Item__c where IsActive__c=True]);
                List<inspectionAnswers> answers =(List<inspectionAnswers>)System.JSON.deserialize(masterAnswers, List<inspectionAnswers>.class);
                List<Warehouse_Daily_Checklist_Item__c> wdciList = new List<Warehouse_Daily_Checklist_Item__c>();
                List<Warehouse_Daily_CheckList__c> wdcList = new List<Warehouse_Daily_CheckList__c>();
                String WarehouseDailyCheckList;
                if(answers.size()>0 && String.isNotBlank(WarehouseDetails)){
                    Warehouse_Daily_CheckList__c wdc = new Warehouse_Daily_CheckList__c();
                    wdc.Warehouse_Detail__c=WarehouseDetails;
                    wdc.Inspected_By__c=InspectedBy;
                    wdc.Inspection_Date__c=system.now();
                    //system.debug('>>>29'+frequencyPicklist);
                    wdc.Frequency__c = frequencyPicklist;
                    wdcList.add(wdc);
                    List<Database.SaveResult> insertResults = Database.insert(wdcList, false);
                    for (Database.SaveResult sr : insertResults) {
                        if (sr.isSuccess()) {
                            WarehouseDailyCheckList=sr.getId();
                        }
                    }
                    if(String.isNotBlank(WarehouseDailyCheckList)){
                        for(inspectionAnswers ins : answers){
                            if(String.isNotBlank(ins.picklist) || String.isNotBlank(ins.remarks)){
                                Warehouse_Daily_Checklist_Item__c wdci = new Warehouse_Daily_Checklist_Item__c();
                                wdci.Warehouse_Daily_CheckList__c=WarehouseDailyCheckList;
                                wdci.Master_Checklist_Item__c=ins.Id;
                                wdci.Answer__c=ins.picklist;
                                wdci.Remarks__c=ins.remarks;
                                wdci.Points_Areas_to_be_checked__c= ChecklistItemMap.size() > 0 && ChecklistItemMap.containsKey(ins.Id) ? ChecklistItemMap.get(ins.Id).Item__c : '';
                                wdciList.add(wdci);
                            }
                        }
                        if(wdciList.size()>0){
                            List<Database.SaveResult> insertChckListItems = Database.insert(wdciList, false);
                            recordId=WarehouseDailyCheckList;
                        }
                    }
                }
           }
        }catch(exception e){
            system.debug('mes=====>'+e.getMessage());
            recordId=e.getMessage();
        }
        return recordId;
    }
    
    //Wrapper class created to Store Master Checklist Item Id, Warehouse Daily Checklist Item Answer(Picklist) & Warehouse Daily Checklist Item Remarks
    public class inspectionAnswers {
        public String id;
        public String picklist;
        public String remarks;
    }
}