2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/Master_Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Master Checklist Item</label>
    <nameField>
        <displayFormat>MCI-{0000}</displayFormat>
        <label>Master Checklist Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Checklist Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Header__c.field-meta.xml
<CustomField>
    <fullName>Header__c</fullName>
    <label>Header</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VISITOR ENTRANCE AREA / LOADING AREA</fullName>
            </value>
            <value>
                <fullName>INTERIOR AREA</fullName>
            </value>
            <value>
                <fullName>RECEPTION AREA / VIEWING ROOMS</fullName>
            </value>
            <value>
                <fullName>TRANSIT AREA</fullName>
            </value>
            <value>
                <fullName>RECEIVING/ RELEASING AREA</fullName>
            </value>
            <value>
                <fullName>VISUAL CHECK AREA（AREA DESIGNATED FOR THE DAY)</fullName>
            </value>
            <value>
                <fullName>TOOL AREA</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT AREA</fullName>
            </value>
            <value>
                <fullName>MATERIAL AREA</fullName>
            </value>
            <value>
                <fullName>CARTON WORKSHOP AREA</fullName>
            </value>
            <value>
                <fullName>STORAGE AREA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <externalId>true</externalId>
    <label>Sequence No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Master_Checklist_Item__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <label>Warehouse Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_Location</valueSetName>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Detail__c/Warehouse_Detail__c.object-meta.xml
<CustomObject>
    <label>Warehouse Detail</label>
    <nameField>
        <label>Warehouse Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Warehouse_Detail__c/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <description>Warehouse Location</description>
    <label>Warehouse Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_Location</valueSetName>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/globalValueSets/Warehouse_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Singapore</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <masterLabel>Warehouse Location</masterLabel>
</GlobalValueSet>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/TestWareHouseChecklist.cls
@isTest
public class TestWareHouseChecklist {
    @isTest
    public static void fetchChecklistItems(){
        Master_Checklist_Item__c mci = new Master_Checklist_Item__c();
        mci.Header__c = 'VISITOR ENTRANCE AREA / LOADING AREA';
        mci.Item__c = 'item';
        mci.Sequence_No__c = 20;
        mci.Mandatory__c = True;
        mci.Warehouse_Location__c = 'China';
        mci.IsActive__c = True;
        insert mci;
        
        Warehouse_Detail__c wd = new Warehouse_Detail__c();
        wd.Warehouse_Location__c = 'Singapore';
        insert wd;
        
        List<WareHouseChecklist.inspectionAnswers> wrapperList = new List<WareHouseChecklist.inspectionAnswers>();
        
        WareHouseChecklist.inspectionAnswers answers = new WareHouseChecklist.inspectionAnswers();
        answers.id = mci.Id;
        answers.picklist = 'Yes';
        answers.remarks = 'None';
        wrapperList.add(answers);
        String var = JSON.serialize(wrapperList); 
        //String var = 'id: \"'+mci.id +'\" \npicklist: \"Yes\" \nremarks: \"3\"';
   		Test.startTest();
        WareHouseChecklist.fetchChecklistItems('China');
        //public static String saveRec(String masterAnswers,String WarehouseDetails,String InspectedBy,String frequencyPicklist)
        WareHouseChecklist.saveRec(var, wd.Id, '1', 'Daily');
        Test.stopTest();
    }
}