2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/Crate_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Crate Line Item</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crate Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>artApp__Transaction__c</referenceTo>
    <relationshipLabel>Crate Line Items</relationshipLabel>
    <relationshipName>Crate_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

Arpan-PersonalOrg/force-app/main/default/classes/crateLineItemTriggerHandler.cls
public class crateLineItemTriggerHandler {
	public static void upsertTransaction(list<Crate_Line_Item__c> CrateLineItemList){
        List<artApp__Transaction__c> TransactionList = new List<artApp__Transaction__c>();
        
        for(Crate_Line_Item__c CrateLineItemObj : CrateLineItemList){
            artApp__Transaction__c TransObj = new artApp__Transaction__c();
            TransObj.Id = CrateLineItemObj.Transaction__c;
            TransactionList.add(TransObj);
        }
        
        transactionTriggerBatch batch = new transactionTriggerBatch(TransactionList);
        Database.executeBatch(batch,50);
    }
}