2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/Freight_Calculator__c.object-meta.xml
<CustomObject>
    <label>Freight Calculator</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Freight No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freight Calculator</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/FreightProductLineItem__c.object-meta.xml
<CustomObject>
    <description>Junction Object to add , Products to Freight Calculator</description>
    <label>FreightProductLineItem</label>
    <nameField>
        <displayFormat>FPI-{00000}</displayFormat>
        <label>FreightProductLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FreightProductLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Freight_Calculator__c.field-meta.xml
<CustomField>
    <fullName>Freight_Calculator__c</fullName>
    <label>Freight Calculator</label>
    <referenceTo>Freight_Calculator__c</referenceTo>
    <relationshipLabel>FreightProductLineItems</relationshipLabel>
    <relationshipName>FreightProductLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Optional__c.field-meta.xml
<CustomField>
    <fullName>Optional__c</fullName>
    <formula>IF(    ISBLANK( Product__c )     ,Optional_Physical__c,Product__r.Optional_Product__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Optional</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>List Price from Price List.</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <formula>IF(ISBLANK( Product__c ),Product_Code_Physical__c,Product__r.ProductCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>IF(ISBLANK( Product__c ),Product_Name_Physical__c ,Product__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/FC_Products_Controller.cls
public with sharing class FC_Products_Controller {

    // Constructor
    public FC_Products_Controller(ApexPages.StandardController controller) {
      this.fc = (Freight_Calculator__c)controller.getSubject();
      loadMProducts(); 
      loadOProducts();  
      m_sc = controller;   
    }

     // public Getter to provide table headers 
     public string[] getmheaders(){
      return new string [] {'Product Name','Product Code','Price'}; 
     }

     // public Getter to provide table headers 
     public string[] getoheaders(){
      return new string [] {'','Product Name','Product Code','Price'}; 
     }

     // public Getter method to retrive Mandatory products 
     public FreightProductLineItem__c[] getMProducts(){ 
      return this.mproducts; 
     }

     // public Getter method to retrive Optional products 
     public FreightProductLineItem__c[] getOProducts(){ 
      return this.oproducts; 
     }

     public pagereference deleteOptProduct() {
        string deleteID = ApexPages.CurrentPage().getParameters().get('deleteId');
        for(FreightProductLineItem__c opt :[SELECT oproducts.Id FROM FreightProductLineItem__c oproducts
                                WHERE  oproducts.Freight_Calculator__c = :fc.id ]){
            If (deleteID == opt.Id) delete opt;
        }
        loadOProducts();
        pageReference pr = new pagereference('/apex/fc_productspage?Id='+ApexPages.CurrentPage().getParameters().get('Id'));
        pr.setRedirect(true);
        return pr;
     }

     // public method to Exit
     public pagereference Cancel(){
      return m_sc.cancel();
     }

     public pagereference Recalculate(){
        return null;
     }

    // Load Mandatory Products
    public void loadMProducts(){
        this.mproducts = [SELECT 
                prod.Product_Name__c ,
                prod.Product_Code__c ,
                prod.Price__c   
              FROM 
              FreightProductLineItem__c prod 
              WHERE 
              prod.Freight_Calculator__c = :fc.id and prod.Optional__c = false];
    }

    // Load Optional Products
    public void loadOProducts(){
        this.oproducts = [SELECT prod.Id, 
                prod.Product_Name__c ,
                prod.Product_Code__c ,
                prod.Price__c   
              FROM 
              FreightProductLineItem__c prod 
              WHERE 
              prod.Freight_Calculator__c = :fc.id and prod.Optional__c = true];
    }

    // Class Variables
    private Freight_Calculator__c fc;
    private FreightProductLineItem__c[] mproducts ;     // Mandatory Products based on Origin & Crate Types
    private FreightProductLineItem__c[] oproducts ;     // Optional Products based on Origin
    ApexPages.standardController m_sc = null;
}