2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/Freight_Calculator__c.object-meta.xml
<CustomObject>
    <label>Freight Calculator</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Freight No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freight Calculator</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Chargeable_Weight__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Weight__c</fullName>
    <description>Chargeable Weight is the Max between Total Artworks Weight and Volumetric Weight</description>
    <formula>IF(Total_Artworks_Weight__c &gt; Volumetric_Weight_Total__c, Total_Artworks_Weight__c, Volumetric_Weight_Total__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Chargeable Weight is the Max between Total Artworks Weight and Volumetric Weight</inlineHelpText>
    <label>Chargeable Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Collection_City__c.field-meta.xml
<CustomField>
    <fullName>Collection_City__c</fullName>
    <label>Collection City</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Singapore (SIN airport)</fullName>
            </value>
            <value>
                <fullName>Japan (NRT airport)</fullName>
            </value>
            <value>
                <fullName>Korea (ICN airport)</fullName>
            </value>
            <value>
                <fullName>Taiwan (TPE airport)</fullName>
            </value>
            <value>
                <fullName>Beijing (PEK airport)</fullName>
            </value>
            <value>
                <fullName>Shanghai (PVG airport)</fullName>
            </value>
            <value>
                <fullName>Australia (SYD airport)</fullName>
            </value>
            <value>
                <fullName>London (LHR airport)</fullName>
            </value>
            <value>
                <fullName>New York (JFK airport)</fullName>
            </value>
            <value>
                <fullName>Los Angeles (LAX airport)</fullName>
            </value>
            <value>
                <fullName>Paris (CDG airport)</fullName>
            </value>
            <value>
                <fullName>Amsterdam (AMS airport)</fullName>
            </value>
            <value>
                <fullName>Hong Kong (HKG airport)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Crate_Height_To_Be__c.field-meta.xml
<CustomField>
    <fullName>Crate_Height_To_Be__c</fullName>
    <formula>Maximum_Height__c + 26</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Crate Height To Be</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Crate_Length_To_Be__c.field-meta.xml
<CustomField>
    <fullName>Crate_Length_To_Be__c</fullName>
    <formula>Maximum_Length__c + 20</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Crate Length To Be</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Crate_Width_To_Be__c.field-meta.xml
<CustomField>
    <fullName>Crate_Width_To_Be__c</fullName>
    <formula>Sum_of_Width__c + 20</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Crate Width To Be</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Destination_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_City__c</fullName>
    <label>Destination City</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hong Kong (HKG airport)</fullName>
                <default>true</default>
                <label>Hong Kong (HKG airport)</label>
            </value>
            <value>
                <fullName>Singapore (SIN airport)</fullName>
            </value>
            <value>
                <fullName>Japan (NRT airport)</fullName>
            </value>
            <value>
                <fullName>Korea (ICN airport)</fullName>
            </value>
            <value>
                <fullName>Taiwan (TPE airport)</fullName>
            </value>
            <value>
                <fullName>Beijing (PEK airport)</fullName>
            </value>
            <value>
                <fullName>Shanghai (PVG airport)</fullName>
            </value>
            <value>
                <fullName>Australia (SYD airport)</fullName>
            </value>
            <value>
                <fullName>London (LHR airport)</fullName>
            </value>
            <value>
                <fullName>New York (JFK airport)</fullName>
            </value>
            <value>
                <fullName>Los Angeles (LAX airport)</fullName>
            </value>
            <value>
                <fullName>Paris (CDG airport)</fullName>
            </value>
            <value>
                <fullName>Amsterdam (AMS airport)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Products_Added__c.field-meta.xml
<CustomField>
    <fullName>Products_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check Box to determine if Products have been added already to the Freight Calculator</description>
    <inlineHelpText>Check Box to determine if Products have been added already to the Freight Calculator</inlineHelpText>
    <label>Products Added</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Total_Artworks_Weight__c.field-meta.xml
<CustomField>
    <fullName>Total_Artworks_Weight__c</fullName>
    <label>Total Artworks Weight</label>
    <summarizedField>Temporary_Artwork__c.Chargeable_Weight__c</summarizedField>
    <summaryForeignKey>Temporary_Artwork__c.Freight_No__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Total_Declared_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Declared_Value__c</fullName>
    <description>Total Declared Value</description>
    <inlineHelpText>Total Declared Value of All Artworks</inlineHelpText>
    <label>Total Declared Value</label>
    <summarizedField>Temporary_Artwork__c.Declared_Value__c</summarizedField>
    <summaryForeignKey>Temporary_Artwork__c.Freight_No__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Type_of_Services__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Services__c</fullName>
    <label>Type of Services</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Airfreight__c/FreightCalc_Airfreight__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Freight Calculator Airfreight Products</description>
    <label>FreightCalc_Airfreight</label>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Airfreight__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Chargeable Weight</description>
    <inlineHelpText>Chargeable Weight</inlineHelpText>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Products__c/FreightCalc_Products__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Freight Calculator Products, Type and Price</description>
    <label>FreightCalc Products</label>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Products__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Active Flag, Wizard should not pull in these Products once they have been made Inactive</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Products__c/fields/Dependent_Field__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Field__c</fullName>
    <label>Dependent Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Products__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Freight Calculator Product Name</description>
    <inlineHelpText>Freight Calculator Product Name</inlineHelpText>
    <label>Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Products__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>Rate per Kg.</description>
    <inlineHelpText>Rate per Kg.</inlineHelpText>
    <label>Rate(per Kg)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/FreightProductLineItem__c.object-meta.xml
<CustomObject>
    <description>Junction Object to add , Products to Freight Calculator</description>
    <label>FreightProductLineItem</label>
    <nameField>
        <displayFormat>FPI-{00000}</displayFormat>
        <label>FreightProductLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FreightProductLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Freight_Calculator__c.field-meta.xml
<CustomField>
    <fullName>Freight_Calculator__c</fullName>
    <label>Freight Calculator</label>
    <referenceTo>Freight_Calculator__c</referenceTo>
    <relationshipLabel>FreightProductLineItems</relationshipLabel>
    <relationshipName>FreightProductLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Optional_Physical__c.field-meta.xml
<CustomField>
    <fullName>Optional_Physical__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Optional</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Product_Code_Physical__c.field-meta.xml
<CustomField>
    <fullName>Product_Code_Physical__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>IF(ISBLANK( Product__c ),Product_Name_Physical__c ,Product__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Product_Name_Physical__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Physical__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Temporary_Crate__c.field-meta.xml
<CustomField>
    <fullName>Temporary_Crate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Temporary Crate</label>
    <referenceTo>Temporary_Crate__c</referenceTo>
    <relationshipLabel>FreightProductLineItems</relationshipLabel>
    <relationshipName>FreightProductLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Crate__c/Temporary_Crate__c.object-meta.xml
<CustomObject>
    <label>Temporary Crate</label>
    <nameField>
        <label>Crate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temporary Crates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Crate__c/fields/Freight_No__c.field-meta.xml
<CustomField>
    <fullName>Freight_No__c</fullName>
    <label>Freight No</label>
    <referenceTo>Freight_Calculator__c</referenceTo>
    <relationshipLabel>Temporary Crates</relationshipLabel>
    <relationshipName>Temporary_Crates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Crate__c/fields/FreightProductLineItem__c.field-meta.xml
<CustomField>
    <fullName>FreightProductLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FreightProductLineItem</label>
    <referenceTo>FreightProductLineItem__c</referenceTo>
    <relationshipLabel>Temporary Crates</relationshipLabel>
    <relationshipName>Temporary_Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Crate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Crate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Crate__c/fields/Volumetric_Weight__c.field-meta.xml
<CustomField>
    <fullName>Volumetric_Weight__c</fullName>
    <formula>( Length__c  *  Width__c  *  Height__c )/6000</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Volumetric Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/FC_Helper.cls
public class FC_Helper
{
    //Class variables
  Freight_Calculator__c fc;
  String FC_type;
  String airport;

    //Constructor
    public FC_Helper(String instanceId)
    {
        this.fc = [SELECT Id, 
                      Total_Artworks_Weight__c,
                      Products_Added__c,
                      Collection_City__c,
                      Destination_City__c,
                      Crate_Length_To_Be__c,
                      Crate_Width_To_Be__c,
                      Crate_Height_To_Be__c,
                      Chargeable_Weight__c, 
                      Total_Declared_Value__c,
                      Type_of_Services__c
                      FROM Freight_Calculator__c 
                      WHERE Id = :instanceId]; 
        
          If ( fc.Products_Added__c == false  || fc.Products_Added__c == null ) {
                    fc.Products_Added__c = true;
                    fc.CurrencyIsoCode = 'HKD';
                    update fc;

                    this.fc = [SELECT Id, 
                      Total_Artworks_Weight__c,
                      Products_Added__c,
                      Collection_City__c,
                      Destination_City__c,
                      Crate_Length_To_Be__c,
                      Crate_Width_To_Be__c,
                      Crate_Height_To_Be__c,
                      Chargeable_Weight__c, 
                      Total_Declared_Value__c,
                      Type_of_Services__c
                      FROM Freight_Calculator__c 
                      WHERE Id = :instanceId];   
          }            

    }         // End Constructor  

    public void insertProducts(String pageFrom){

         deleteProducts();

         If (fc.Collection_City__c == 'Hong Kong (HKG airport)') {
                    FC_type = 'Origin';
                    airport = fc.Destination_City__c;
                    fc.Type_of_Services__c = 'Origin handling in ' + airport + ' (via air)'; 
         }    
         Else{
                    FC_type = 'Destination'; 
                    airport = fc.Collection_City__c;
                    fc.Type_of_Services__c = 'Destination handling in ' + airport + ' (via air)';
         } 
               
         update fc;

         AddProducts();
         
         if (FC_type == 'Origin') 
          {
              AirFreightProducts();

              /*if (pageFrom == 'CratePage')*/ CrateProducts();                      
          }    

    }    // End Function insertProducts..  


    //Function to add Freight Products, based on Origin
    public void AddProducts(){
        
      FreightProductLineItem__c[] fp = new List<FreightProductLineItem__c>();
      List<FreightCalc_Products__c> products = FreightCalc_Products__c.getAll().values();
      Decimal cost ;
              
        for(FreightCalc_Products__c p :products) {
            If (  (    ( FC_type =='Origin' && p.Type__c == 'Export' )
                    || ( FC_type =='Destination' &&  p.Type__c == 'Import'  )
                    || (p.Type__c != 'Export'  && p.Type__c != 'Import')
                  ) && p.Active__c == TRUE 
                ) {

                    If (p.Dependent_Field__c == 'CustomLogic-Crate'){

                            Temporary_Crate__c[] crates  = [SELECT crt.Volumetric_Weight__c,
                                                                   crt.Type__c 
                                                              FROM Temporary_Crate__c crt
                                                              WHERE crt.Freight_No__c = :fc.Id  AND
                                                              crt.Volumetric_Weight__c  > 150];

                            for(Temporary_Crate__c crt:crates){

                                    FreightProductLineItem__c fp_line = new FreightProductLineItem__c(
                                    Freight_Calculator__c =fc.Id,
                                    CurrencyIsoCode = 'HKD',
                                    Product_Name_Physical__c = p.Product_Name__c,
                                    Product_Code_Physical__c = p.Type__c, 
                                    Optional_Physical__c     = p.Optional__c,
                                    Price__c = p.Price__c );
                                    fp.add(fp_line);  
                                                
                           }
                    }Else {

                      FreightProductLineItem__c fp_line = new FreightProductLineItem__c(
                      Freight_Calculator__c =fc.Id,
                      CurrencyIsoCode = 'HKD',
                      Product_Name_Physical__c = p.Product_Name__c,
                      Product_Code_Physical__c = p.Type__c, 
                      Optional_Physical__c     = p.Optional__c );

                      insert fp_line;

                      If (p.Dependent_Field__c == 'Chargeable_Weight__c') {
                            
                            cost = p.Rate__c * fc.Chargeable_Weight__c;
                            If ( cost > p.Price__c ) fp_line.Price__c = cost;  
                            Else fp_line.Price__c = p.Price__c;

                      }Else If (p.Dependent_Field__c == 'Total_Declared_Value__c'){
                     
                            fp_line.Price__c = p.Rate__c * fc.Total_Declared_Value__c;
                            System.debug('Cost : ' + fp_line.Price__c + ' Rate: ' + p.Rate__c + ' Declared Value: ' + fc.Total_Declared_Value__c  );

                      }Else If (p.Dependent_Field__c == 'M3') {
                            
                            cost = p.Rate__c * ( (fc.Crate_Length_To_Be__c * fc.Crate_Width_To_Be__c * fc.Crate_Height_To_Be__c) / 1000000 ); 
                            If ( cost > p.Price__c ) fp_line.Price__c = cost;  
                            Else fp_line.Price__c = p.Price__c;

                      }Else  fp_line.Price__c = p.Price__c ;

                      

                      //fp.add(fp_line);
                      update fp_line;
                   }
                }  
          }          

        //insert fp;
    } // Add Products

  

  public void AirFreightProducts(){

                 FreightCalc_Airfreight__c prd =     [SELECT 
                              p.Airport_Name__c,
                              p.Price__c,
                              p.Weight__c
                              FROM FreightCalc_Airfreight__c p 
                              WHERE p.Airport_Name__c = :airport AND 
                              p.Weight__c >= :fc.Total_Artworks_Weight__c  
                              ORDER BY p.Weight__c LIMIT 1];

                FreightProductLineItem__c fp_line = new FreightProductLineItem__c(
                Freight_Calculator__c = fc.Id,
                Product_Name_Physical__c = prd.Airport_Name__c,
                Product_Code_Physical__c = 'Airfreight',
                Price__c = prd.Price__c ,
                CurrencyIsoCode = 'HKD'  );   

                insert fp_line;    
  
  }  // End Airfreight Products


  // Function to delete all Temporary Crates associated with a Freight Calculator Record....
  public void refreshCrate() {

    Temporary_Crate__c[] allCrates = [SELECT crt.Id FROM Temporary_Crate__c  crt
                         WHERE crt.Freight_No__c = :fc.Id ]; 

    FreightProductLineItem__c[] crateProducts =   [SELECT fprd.Id FROM FreightProductLineItem__c  fprd
                         WHERE fprd.Product_Code__c  = 'Crate' and fprd.Freight_Calculator__c = :fc.Id ];                    
    
        delete allCrates;
        delete crateProducts;

    Temporary_Crate__c crt = new Temporary_Crate__c();
    crt.Freight_No__c = fc.Id;
    crt.Type__c = 'Crate';
    crt.FreightProduct_Added__c = FALSE;
    crt.Length__c = fc.Crate_Length_To_Be__c;
    crt.Width__c = fc.Crate_Width_To_Be__c;
    crt.Height__c = fc.Crate_Height_To_Be__c;

    insert crt; 

  }  // End Function Refresh Crate deleteProducts  

  // Function to delete all Products associated with the Freight calculator
  public void deleteProducts() {

    FreightProductLineItem__c[] crateProducts =   [SELECT fprd.Id FROM FreightProductLineItem__c  fprd
                         WHERE fprd.Freight_Calculator__c = :fc.Id ];                    
    
    delete crateProducts;

  }  // End Function delete Products  

    public void CrateProducts(){
      
      Temporary_Crate__c[] crates;
      FreightProductLineItem__c[] fprds = new List<FreightProductLineItem__c>();
      Product2 prd;

         try{
      
            crates = [ SELECT c.Id,
                              c.Type__c,
                              c.Length__c,
                              c.Width__c,
                              c.Height__c,
                              c.FreightProduct_Added__c,
                              c.Volumetric_Weight__c
                              FROM Temporary_Crate__c c 
                              WHERE c.Freight_No__c = :fc.Id 
                               ];
                               
                             


             for (Temporary_Crate__c crt: crates ){

                FreightProductLineItem__c fpl = new FreightProductLineItem__c();
                fpl.Freight_Calculator__c = fc.Id;
                fpl.Product_Code_Physical__c = crt.Type__c;
                fpl.CurrencyIsoCode = 'HKD';

                If ( crt.Type__c == 'Crate') {   
     
                      fpl.Product_Name_Physical__c = 'Custom Crate';  
                      Decimal toround = ( crt.Length__c  *  crt.Width__c *  crt.Height__c ) / 1000000;
                      Decimal rounded = toRound.setScale(2, RoundingMode.HALF_UP);
                      fpl.Price__c = 2800 * rounded; 
                      
                   } else {

                      fpl.Product_Name_Physical__c = 'Manually Made Box';  
                            
                      If ( crt.Length__c  > 200 || crt.Height__c > 200 ) fpl.Price__c = 500;
                      else fpl.Price__c = 250;                              
                   }     

                   crt.FreightProduct_Added__c = TRUE;
                   fprds.add(fpl);                   

                }                  
          
             insert fprds;
             update crates; 
        }catch(Exception e ){
          
        }     
 
  }  // End Crate Products

}  // End Class FC_Helper