2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/Freight_Calculator__c.object-meta.xml
<CustomObject>
    <label>Freight Calculator</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Freight No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freight Calculator</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Collection_City__c.field-meta.xml
<CustomField>
    <fullName>Collection_City__c</fullName>
    <label>Collection City</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Singapore (SIN airport)</fullName>
            </value>
            <value>
                <fullName>Japan (NRT airport)</fullName>
            </value>
            <value>
                <fullName>Korea (ICN airport)</fullName>
            </value>
            <value>
                <fullName>Taiwan (TPE airport)</fullName>
            </value>
            <value>
                <fullName>Beijing (PEK airport)</fullName>
            </value>
            <value>
                <fullName>Shanghai (PVG airport)</fullName>
            </value>
            <value>
                <fullName>Australia (SYD airport)</fullName>
            </value>
            <value>
                <fullName>London (LHR airport)</fullName>
            </value>
            <value>
                <fullName>New York (JFK airport)</fullName>
            </value>
            <value>
                <fullName>Los Angeles (LAX airport)</fullName>
            </value>
            <value>
                <fullName>Paris (CDG airport)</fullName>
            </value>
            <value>
                <fullName>Amsterdam (AMS airport)</fullName>
            </value>
            <value>
                <fullName>Hong Kong (HKG airport)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Destination_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_City__c</fullName>
    <label>Destination City</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hong Kong (HKG airport)</fullName>
                <default>true</default>
                <label>Hong Kong (HKG airport)</label>
            </value>
            <value>
                <fullName>Singapore (SIN airport)</fullName>
            </value>
            <value>
                <fullName>Japan (NRT airport)</fullName>
            </value>
            <value>
                <fullName>Korea (ICN airport)</fullName>
            </value>
            <value>
                <fullName>Taiwan (TPE airport)</fullName>
            </value>
            <value>
                <fullName>Beijing (PEK airport)</fullName>
            </value>
            <value>
                <fullName>Shanghai (PVG airport)</fullName>
            </value>
            <value>
                <fullName>Australia (SYD airport)</fullName>
            </value>
            <value>
                <fullName>London (LHR airport)</fullName>
            </value>
            <value>
                <fullName>New York (JFK airport)</fullName>
            </value>
            <value>
                <fullName>Los Angeles (LAX airport)</fullName>
            </value>
            <value>
                <fullName>Paris (CDG airport)</fullName>
            </value>
            <value>
                <fullName>Amsterdam (AMS airport)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/FreightProductLineItem__c.object-meta.xml
<CustomObject>
    <description>Junction Object to add , Products to Freight Calculator</description>
    <label>FreightProductLineItem</label>
    <nameField>
        <displayFormat>FPI-{00000}</displayFormat>
        <label>FreightProductLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FreightProductLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightProductLineItem__c/fields/Freight_Calculator__c.field-meta.xml
<CustomField>
    <fullName>Freight_Calculator__c</fullName>
    <label>Freight Calculator</label>
    <referenceTo>Freight_Calculator__c</referenceTo>
    <relationshipLabel>FreightProductLineItems</relationshipLabel>
    <relationshipName>FreightProductLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/FC_Products_ControllerTest.cls
@isTest
public class FC_Products_ControllerTest {
    static testmethod void FC_Products_Controller(){
        
        Freight_Calculator__c fc = new Freight_Calculator__c();
        fc.Collection_City__c = 'Singapore (SIN airport)';
        fc.Destination_City__c = 'Hong Kong (HKG airport)';
        insert fc;
        
        FreightProductLineItem__c fprod = new FreightProductLineItem__c();
        fprod.Freight_Calculator__c = 'a0N11000003iRwA';
        fprod.CurrencyIsoCode = 'SGD - Singapore Dollar';
        
        PageReference PageRef = Page.FC_ProductsPage;
        test.setCurrentPage(PageRef);
        ApexPages.CurrentPage().getparameters().put('id', fc.id);
        ApexPages.StandardController sc = new ApexPages.standardController(fc);
        
        FC_Products_Controller ctrl = new FC_Products_Controller(sc); 
        ctrl.loadOProducts();
        ctrl.getmheaders();
        ctrl.getoheaders();
        ctrl.getMProducts();
        ctrl.getOProducts();
        ctrl.deleteOptProduct();
        ctrl.Recalculate();
        ctrl.Cancel();
        //getoheaders('Painting Installation','Import','100');
        //FreightProductLineItem__c ctrl = new FreightProductLineItem__c(sc); 
    }

}