2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/Freight_Calculator__c.object-meta.xml
<CustomObject>
    <label>Freight Calculator</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Freight No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freight Calculator</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Chargeable_Weight__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Weight__c</fullName>
    <description>Chargeable Weight is the Max between Total Artworks Weight and Volumetric Weight</description>
    <formula>IF(Total_Artworks_Weight__c &gt; Volumetric_Weight_Total__c, Total_Artworks_Weight__c, Volumetric_Weight_Total__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Chargeable Weight is the Max between Total Artworks Weight and Volumetric Weight</inlineHelpText>
    <label>Chargeable Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Collection_City__c.field-meta.xml
<CustomField>
    <fullName>Collection_City__c</fullName>
    <label>Collection City</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Singapore (SIN airport)</fullName>
            </value>
            <value>
                <fullName>Japan (NRT airport)</fullName>
            </value>
            <value>
                <fullName>Korea (ICN airport)</fullName>
            </value>
            <value>
                <fullName>Taiwan (TPE airport)</fullName>
            </value>
            <value>
                <fullName>Beijing (PEK airport)</fullName>
            </value>
            <value>
                <fullName>Shanghai (PVG airport)</fullName>
            </value>
            <value>
                <fullName>Australia (SYD airport)</fullName>
            </value>
            <value>
                <fullName>London (LHR airport)</fullName>
            </value>
            <value>
                <fullName>New York (JFK airport)</fullName>
            </value>
            <value>
                <fullName>Los Angeles (LAX airport)</fullName>
            </value>
            <value>
                <fullName>Paris (CDG airport)</fullName>
            </value>
            <value>
                <fullName>Amsterdam (AMS airport)</fullName>
            </value>
            <value>
                <fullName>Hong Kong (HKG airport)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Destination_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_City__c</fullName>
    <label>Destination City</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hong Kong (HKG airport)</fullName>
                <default>true</default>
                <label>Hong Kong (HKG airport)</label>
            </value>
            <value>
                <fullName>Singapore (SIN airport)</fullName>
            </value>
            <value>
                <fullName>Japan (NRT airport)</fullName>
            </value>
            <value>
                <fullName>Korea (ICN airport)</fullName>
            </value>
            <value>
                <fullName>Taiwan (TPE airport)</fullName>
            </value>
            <value>
                <fullName>Beijing (PEK airport)</fullName>
            </value>
            <value>
                <fullName>Shanghai (PVG airport)</fullName>
            </value>
            <value>
                <fullName>Australia (SYD airport)</fullName>
            </value>
            <value>
                <fullName>London (LHR airport)</fullName>
            </value>
            <value>
                <fullName>New York (JFK airport)</fullName>
            </value>
            <value>
                <fullName>Los Angeles (LAX airport)</fullName>
            </value>
            <value>
                <fullName>Paris (CDG airport)</fullName>
            </value>
            <value>
                <fullName>Amsterdam (AMS airport)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Airfreight__c/FreightCalc_Airfreight__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Freight Calculator Airfreight Products</description>
    <label>FreightCalc_Airfreight</label>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Airfreight__c/fields/Airport_Name__c.field-meta.xml
<CustomField>
    <fullName>Airport_Name__c</fullName>
    <label>Airport Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Airfreight__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price / Rate</description>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/FreightCalc_Airfreight__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Chargeable Weight</description>
    <inlineHelpText>Chargeable Weight</inlineHelpText>
    <label>Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Artwork__c/Temporary_Artwork__c.object-meta.xml
<CustomObject>
    <label>Temporary Artwork</label>
    <nameField>
        <displayFormat>F-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temporary Artworks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Artwork__c/fields/Freight_No__c.field-meta.xml
<CustomField>
    <fullName>Freight_No__c</fullName>
    <label>Freight No</label>
    <referenceTo>Freight_Calculator__c</referenceTo>
    <relationshipLabel>Temporary Artworks</relationshipLabel>
    <relationshipName>Temporary_Artworks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/classes/FC_Crates_ControllerTest.cls
@isTest
public class FC_Crates_ControllerTest {
    static testmethod void FC_Crates_ControllerTest(){
        Freight_Calculator__c fc = new Freight_Calculator__c();
        fc.Collection_City__c = 'Singapore (SIN airport)';
        fc.Destination_City__c = 'Hong Kong (HKG airport)';
        insert fc;
        
        Temporary_Artwork__c art = new Temporary_Artwork__c();
        art.Freight_No__c = fc.Id;
        art.Length__c =100;
        art.Breadth__c = 50;
        art.Height__c = 20;
        art.Chargeable_Weight__c = 12;
        insert art;
        
        FreightCalc_Airfreight__c fa = new FreightCalc_Airfreight__c();
        fa.Name = 'Custom_Settings';
        fa.Airport_Name__c = 'Singapore (SIN airport)';//Hong Kong (HKG airport)';
        fa.Weight__c = 15;
        fa.Price__c = 100;
        insert fa;
        
        PageReference PageRef = Page.FreightCalc_CratesPage; 
        test.setCurrentPage(PageRef);
        ApexPages.CurrentPage().getparameters().put('id', fc.id);
        ApexPages.StandardController sc = new ApexPages.standardController(fc);
        
        FC_Crates_Controller ctrl = new FC_Crates_Controller(sc); 
        ctrl.newCrate();
        ctrl.saveCrates();
        ctrl.deleteCrate();
        ctrl.getCrates();
        ctrl.Back();
        ctrl.Cancel();
        ctrl.getheaders();
        ctrl.GoProductsPage();
    }
}