2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/Freight_Calculator__c.object-meta.xml
<CustomObject>
    <label>Freight Calculator</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>Freight No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freight Calculator</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Freight_Calculator__c/fields/Chargeable_Weight__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Weight__c</fullName>
    <description>Chargeable Weight is the Max between Total Artworks Weight and Volumetric Weight</description>
    <formula>IF(Total_Artworks_Weight__c &gt; Volumetric_Weight_Total__c, Total_Artworks_Weight__c, Volumetric_Weight_Total__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Chargeable Weight is the Max between Total Artworks Weight and Volumetric Weight</inlineHelpText>
    <label>Chargeable Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Artwork__c/Temporary_Artwork__c.object-meta.xml
<CustomObject>
    <label>Temporary Artwork</label>
    <nameField>
        <displayFormat>F-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temporary Artworks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Artwork__c/fields/Declared_Value__c.field-meta.xml
<CustomField>
    <fullName>Declared_Value__c</fullName>
    <description>Declared Value of Artworks</description>
    <inlineHelpText>Declared Value of Artworks</inlineHelpText>
    <label>Declared Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Artwork__c/fields/Freight_No__c.field-meta.xml
<CustomField>
    <fullName>Freight_No__c</fullName>
    <label>Freight No</label>
    <referenceTo>Freight_Calculator__c</referenceTo>
    <relationshipLabel>Temporary Artworks</relationshipLabel>
    <relationshipName>Temporary_Artworks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Temporary_Artwork__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2 D</fullName>
            </value>
            <value>
                <fullName>3 D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Arpan-PersonalOrg/force-app/main/default/classes/FC_Artworks_Controller.cls
public class FC_Artworks_Controller {
 
ApexPages.StandardController fc_controller;
public decimal sumOfCW{get;set;}
  // Constructor
 public FC_Artworks_Controller(ApexPages.StandardController controller) {
      
//      this.fc = (Freight_Calculator__c)controller.getSubject();
     fc_controller = controller;
     this.fc = (Freight_Calculator__c)fc_controller.getSubject();
      loadArtworks();                                                                                                                                                                                                                                   
      m_sc = controller;   
 }
 
  // Action Method called from page button
 public pagereference saveArtworks() { 
      sumOfCW = 0.0;
      for(Temporary_Artwork__c a:this.artworks){
      
          a.CurrencyIsoCode = 'HKD';
          
          if(a.Chargeable_Weight__c == null || a.Chargeable_Weight__c == 0){
          
              Decimal h = a.Height__c;
              Decimal l = a.Breadth__c;
              Decimal b = a.Length__c;          
          
              if(h != null && l != null && b != null){
                  a.Chargeable_Weight__c = h*l*b;
              }else if(h != null && l != null){
                  a.Chargeable_Weight__c = h*l;
              }else if(b != null && l != null){
                  a.Chargeable_Weight__c = l*b;
              }else if(b != null && h != null){
                  a.Chargeable_Weight__c = h*b;
              }else if(b != null){
                  a.Chargeable_Weight__c = b;
              }else if(h != null){
                  a.Chargeable_Weight__c = h;
              }else if(l != null){
                  a.Chargeable_Weight__c = l;
              } 
              if(a.Chargeable_Weight__c != null){
                  a.Chargeable_Weight__c = a.Chargeable_Weight__c/6000;                     
                  a.Chargeable_Weight__c = a.Chargeable_Weight__c.setScale(2);                   
              }                
          }    
          
          sumOfCW  += ((a.Chargeable_Weight__c !=null)?a.Chargeable_Weight__c:0.0);   
          if(sumOfCW > 500){
              ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Sum of all Chargeable Weight is more than 500.'));
              return null;
          }   
      }
      upsert this.artworks;
     // fc_controller.reset();
      //fc_controller.addFields(new LIST<String> {'Id'});
     // PageReference curPage = ApexPages.CurrentPage();
      //curPage.setRedirect(TRUE);
      return null;
 }
 
  // Action Method called from page button
 public pagereference newArtwork() { 
  Temporary_Artwork__c artwork = new Temporary_Artwork__c();
  artwork.Freight_No__c =this.fc.id; 
  artwork.CurrencyIsoCode = 'HKD';
  artworks.add (artwork);
  return null;
 }
 
// Action Method called from page button
 public pagereference deleteArtwork() { 
  string artworkID = ApexPages.CurrentPage().getParameters().get('deleteId');
  try{
    for(Temporary_Artwork__c art :[SELECT arts.Id FROM Temporary_Artwork__c arts 
                                WHERE  arts.Freight_No__c = :fc.id ]){
        If (artworkID == art.Id) delete art;
    }
  }catch(Exception e){
  
  }  
  loadArtworks();
  return null;
 }

 public pagereference Cancel(){
    return m_sc.cancel();
 }

 public pagereference GoProductsPage(){
  this.saveArtworks();
  Temporary_Artwork__c[] artworks = getArtworks();
  if(artworks.size() <= 0 ){    
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'There are no artworks created to go forward.'));
      return null;
  }else if(sumOfCW > 500){
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Sum of all Chargeable Weight is more than 500.'));
      return null;
  }else{
      FC_Helper fc_helper =  new FC_Helper(fc.Id); 
      //fc_helper.deleteProducts();
      fc_helper.insertProducts('ArtworksPage');
         
      PageReference productsPage = Page.FC_ProductsPage;
      productsPage.getParameters().put('Id',fc.Id);
      return  productsPage;
  }
  return null; 
}

 public pagereference GoCratePage(){
  this.saveArtworks();
  Temporary_Artwork__c[] artworks = getArtworks();
  if(artworks.size() <= 0 ){    
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'There are no artworks created to go forward.'));
      return null;
  }else if(sumOfCW > 500){
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Sum of all Chargeable Weight is more than 500.'));
      return null;
  }else{     
      FC_Helper fc_helper = new FC_Helper(fc.Id); 
      fc_helper.refreshCrate();
      PageReference cratePage = Page.FreightCalc_CratesPage;
      cratePage.getParameters().put('Id',fc.Id);
      return  cratePage;
  }
  return null;
 }

  // public Getter to provide table headers 
 public string[] getheaders(){
  return new string [] {'','Type','Length','Breadth', 'Height','Chargeable Weight','Declared Value'};
 }

 // public Getter method to retrive Artwork records
 public Temporary_Artwork__c[] getArtworks(){ 
  return this.artworks; 
 }

 // single internal method to load Artworks
 private void loadArtworks() {
    this.artworks = [SELECT  
        artworks.Id, 
        artworks.Type__c ,
        artworks.Length__c ,
        artworks.Breadth__c ,
        artworks.Height__c ,
        artworks.Chargeable_Weight__c,
        artworks.Declared_Value__c
      FROM 
      Temporary_Artwork__c artworks
      WHERE 
      artworks.Freight_No__c = :fc.id ];
 }

// class variables
 private Freight_Calculator__c fc;
 private Temporary_Artwork__c[] artworks ;    
 ApexPages.standardController m_sc = null;
}