2nd training/Community/Community/Community1/force-app/main/default/objects/Carton_Fabrication__c/Carton_Fabrication__c.object-meta.xml
<CustomObject>
    <label>Carton Fabrication</label>
    <nameField>
        <displayFormat>CRB-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carton Fabrications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Carton_Fabrication__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>Job_Reference__r.Client_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client 客户名称</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Carton_Fabrication__c/fields/CS_Contact_No__c.field-meta.xml
<CustomField>
    <fullName>CS_Contact_No__c</fullName>
    <formula>IF( AND( Owner:User.Phone != NULL, Owner:User.MobilePhone == NULL), Owner:User.Phone, 
IF(AND( Owner:User.Phone == NULL, Owner:User.MobilePhone != NULL), Owner:User.MobilePhone, 
IF(AND( Owner:User.Phone != NULL, Owner:User.MobilePhone != NULL), Owner:User.Phone, null 
) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CS Contact No.:</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Carton_Fabrication__c/fields/Job_Reference__c.field-meta.xml
<CustomField>
    <fullName>Job_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Reference 工作编号</label>
    <referenceTo>Job_Reference__c</referenceTo>
    <relationshipLabel>Carton Fabrications</relationshipLabel>
    <relationshipName>Carton_Fabrications</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Carton_Fabrication__c/fields/Required_Date__c.field-meta.xml
<CustomField>
    <fullName>Required_Date__c</fullName>
    <label>Required Date 需要日期</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/Crafting_Details__c.object-meta.xml
<CustomObject>
    <label>Crate Details</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Crating Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crate Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/CrateInstructionLineItem__c/CrateInstructionLineItem__c.object-meta.xml
<CustomObject>
    <label>CartonFabricationLineItem</label>
    <nameField>
        <displayFormat>CLI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CrateInstructionLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/CrateInstructionLineItem__c/fields/Breadth_inch__c.field-meta.xml
<CustomField>
    <fullName>Breadth_inch__c</fullName>
    <label>Breadth (inch)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/CrateInstructionLineItem__c/fields/Carton_Fabrication__c.field-meta.xml
<CustomField>
    <fullName>Carton_Fabrication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carton Fabrication</label>
    <referenceTo>Carton_Fabrication__c</referenceTo>
    <relationshipName>CrateInstructionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/CrateInstructionLineItem__c/fields/Carton_Lining__c.field-meta.xml
<CustomField>
    <fullName>Carton_Lining__c</fullName>
    <label>Carton Lining</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Silicon Paper (油紙)</fullName>
            </value>
            <value>
                <fullName>PE 1”</fullName>
            </value>
            <value>
                <fullName>PE 1.5”</fullName>
            </value>
            <value>
                <fullName>PE 2”</fullName>
            </value>
            <value>
                <fullName>Grey Sponge 1”</fullName>
            </value>
            <value>
                <fullName>Grey Sponge 1.5”</fullName>
            </value>
            <value>
                <fullName>Grey Sponge 2”</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/CrateInstructionLineItem__c/fields/Carton_Type__c.field-meta.xml
<CustomField>
    <fullName>Carton_Type__c</fullName>
    <label>Carton Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shoe Box (天地)</fullName>
            </value>
            <value>
                <fullName>Cake Box (西餅)</fullName>
            </value>
            <value>
                <fullName>Envelope (拉盒)</fullName>
            </value>
            <value>
                <fullName>Others (其他)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/CrateInstructionLineItem__c/fields/Height_inch__c.field-meta.xml
<CustomField>
    <fullName>Height_inch__c</fullName>
    <label>Height (inch)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/CrateInstructionLineItem__c/fields/Length_inch__c.field-meta.xml
<CustomField>
    <fullName>Length_inch__c</fullName>
    <label>Length (inch)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/Job_Reference__c.object-meta.xml
<CustomObject>
    <description>Stores the Job reference no</description>
    <label>Job Reference</label>
    <nameField>
        <label>Job Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/classes/CartonFabricationPageController.cls
public with sharing class CartonFabricationPageController {
    
    Carton_Fabrication__c ciRec;
    public Carton_Fabrication__c crateIns{get; set;}
    public list<Crafting_Details__c> craftingDetailsList {get;set;}
    public list<CrateInstructionLineItem__c> crateinstructionItemList {get;set;}
    
    public CartonFabricationPageController(ApexPages.StandardController sc)
    {
        ciRec = (Carton_Fabrication__c)sc.getRecord();
        craftingDetailsList = new list<Crafting_Details__c>();
        String idstr=string.valueof(ciRec);
        crateinstructionItemList=[select Breadth_inch__c,Carton_Lining__c,Carton_Type__c,Height_inch__c,Length_inch__c,Additional_Notes__c from CrateInstructionLineItem__c where Carton_Fabrication__c=:ciRec.id];
        crateIns = [Select Id,CreatedDate, Name, Client__c, Job_Reference__c,Job_Reference__r.Name,  Required_Date__c, CreatedById,CreatedBy.Name,CS_Contact_No__c from Carton_Fabrication__c where ID =:ciRec.id];                            
    } 
    
}