2nd training/Community/Community/Community1/force-app/main/default/objects/Carton_Fabrication__c/Carton_Fabrication__c.object-meta.xml
<CustomObject>
    <label>Carton Fabrication</label>
    <nameField>
        <displayFormat>CRB-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carton Fabrications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Carton_Fabrication__c/fields/Required_Date__c.field-meta.xml
<CustomField>
    <fullName>Required_Date__c</fullName>
    <label>Required Date 需要日期</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/CrateInstructionLineItem__c/CrateInstructionLineItem__c.object-meta.xml
<CustomObject>
    <label>CartonFabricationLineItem</label>
    <nameField>
        <displayFormat>CLI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CrateInstructionLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/CrateInstructionLineItem__c/fields/Carton_Fabrication__c.field-meta.xml
<CustomField>
    <fullName>Carton_Fabrication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carton Fabrication</label>
    <referenceTo>Carton_Fabrication__c</referenceTo>
    <relationshipName>CrateInstructionLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/CartonFabricationPageControllerTest.cls
@istest
public class CartonFabricationPageControllerTest {
    public static testmethod void mytest2(){
        Carton_Fabrication__c cb=new Carton_Fabrication__c();
        cb.Required_Date__c=system.Today();
        //cb.name='TestName';
        insert cb;
        
        CrateInstructionLineItem__c cli=new CrateInstructionLineItem__c();
        
        cli.Carton_Fabrication__c=cb.id;
        insert cli;
        
          ApexPages.StandardController sc = new ApexPages.StandardController(cb);
        CartonFabricationPageController cpc=new CartonFabricationPageController(sc);
        
        PageReference pageRef = Page.cartonfabricationpage;
       
        Test.setCurrentPage(pageRef);
        CrateInstructionLineItemDetailController cic=new CrateInstructionLineItemDetailController();
    cic.languageCode='0001';
    }

}