2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/fields/Storage_Facility__c.field-meta.xml
<CustomField>
    <fullName>Storage_Facility__c</fullName>
    <label>Storage Facility</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>* Not in Storage</fullName>
            </value>
            <value>
                <fullName>ATL, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Cheung Hing Shing, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Chun Sing, Hong Kong</fullName>
            </value>
            <value>
                <fullName>CITIC, Hong Kong</fullName>
            </value>
            <value>
                <fullName>CityCentre Storage, Singapore</fullName>
            </value>
            <value>
                <fullName>Display Site</fullName>
            </value>
            <value>
                <fullName>Gehua</fullName>
            </value>
            <value>
                <fullName>Global Gateway, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hellmann, Hong Kong</fullName>
            </value>
            <value>
                <fullName>HKCEC</fullName>
            </value>
            <value>
                <fullName>In Passage</fullName>
            </value>
            <value>
                <fullName>Jaguar, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Jin Ma Building, Beijing</fullName>
            </value>
            <value>
                <fullName>Kong Nam, Hong Kong</fullName>
            </value>
            <value>
                <fullName>LinJi Building, Beijing</fullName>
            </value>
            <value>
                <fullName>Mapletree, Hong Kong</fullName>
            </value>
            <value>
                <fullName>MBS</fullName>
            </value>
            <value>
                <fullName>Richwealth, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Shanghai Storage, Shanghai</fullName>
            </value>
            <value>
                <fullName>Singapore FreePort, Singapore</fullName>
            </value>
            <value>
                <fullName>Success Building, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Terrada S Building</fullName>
            </value>
            <value>
                <fullName>Tsing Yi, Hong Kong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/recordTypes/Artmove.recordType-meta.xml
<RecordType>
    <fullName>Artmove</fullName>
    <active>true</active>
    <label>Artmove</label>
</RecordType>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/locationTriggerHandler_Test.cls
@isTest
public class locationTriggerHandler_Test {
    static testmethod void dotest(){
        
        list<Location__c> Loc_list = new list<Location__c>();
        Id  locRTid = Schema.SObjectType.Location__c.getRecordTypeInfosByName().get('Artmove').getRecordTypeId();
        Location__c location1 = new Location__c();
        location1.Name = 'testlocation2';
        location1.CurrencyIsoCode = 'SGD';
        location1.RecordTypeId = locRTid;
        Loc_list.add(location1);
        
        
        
        Location__c location2 = new Location__c();
        location2.Name = 'ATL-1010020';
        location2.CurrencyIsoCode = 'SGD';
        location2.RecordTypeId = locRTid;
        location2.Storage_Facility__c = 'ATL, Hong Kong';
        Loc_list.add(location2);
        insert loc_list;
        
        locationTriggerHandler.upsertlocation(loc_list);
    }
}