2nd training/Community/Community/Community1/force-app/main/default/objects/Account/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <description>Overseas trading partners that reciprocrates tonnage with us.</description>
    <label>Agent</label>
</RecordType>

2nd training/Community/Community/Community1/force-app/main/default/objects/Contact/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <description>Overseas trading partners (agents) that reciprocrates tonnage with us</description>
    <label>Agent</label>
</RecordType>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/Rate_Reply__c.object-meta.xml
<CustomObject>
    <description>Inbound rate reply</description>
    <label>Rate Reply</label>
    <nameField>
        <displayFormat>RR/{YY}/{MM}/{0000}</displayFormat>
        <label>Rate Reply ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Replies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Agent_Email__c.field-meta.xml
<CustomField>
    <fullName>Agent_Email__c</fullName>
    <defaultValue>&quot;Do not enter anything&quot;</defaultValue>
    <label>Agent Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of agent requesting rates</description>
    <inlineHelpText>Name of agent requesting rates</inlineHelpText>
    <label>Agent Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rate Reply</relationshipLabel>
    <relationshipName>R00N2000000121wnEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Select the currency used for the quotation</description>
    <inlineHelpText>Currency to be used for the quotation</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date of quotation</description>
    <inlineHelpText>Date of quotation</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <label>Initials</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Quote_Reference2__c.field-meta.xml
<CustomField>
    <fullName>Quote_Reference2__c</fullName>
    <formula>quote_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Reference</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Quote_Validity_days__c.field-meta.xml
<CustomField>
    <fullName>Quote_Validity_days__c</fullName>
    <defaultValue>&quot;60&quot;</defaultValue>
    <description>Number of days quote is valid</description>
    <inlineHelpText>Number of days quote is valid</inlineHelpText>
    <label>Quote Validity (days)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/classes/rateReplyAttach.cls
public class rateReplyAttach {
        public Rate_Reply__c rr { get; private set;}
        private ApexPages.Standardcontroller controller;
        
        id rateReplyID;
        public rateReplyAttach (){
                rateReplyID = ApexPages.currentPage().getParameters().get('id');
                rr = [Select r.id, r.recordTypeId, r.RecordType.Name, r.Quote_Reference2__c From 
                Rate_Reply__c r Where id =: rateReplyID limit 1];
        }
        public rateReplyAttach (ApexPages.StandardController c) {
                controller = c;
                rateReplyID = c.getRecord().id;
                rr = [Select r.id, r.recordTypeId, r.RecordType.Name, r.Quote_Reference2__c From 
                Rate_Reply__c r Where id =: rateReplyID limit 1]; 
        }
        
        public PageReference attachQuote() {
                String pageURL = '';
                
                /* Set page definition */
                if(rr.RecordType.Name == 'DS Air Shipment') {
                        pageURL = '/apex/rateReplyDS';
                } else if (rr.RecordType.Name == 'DS Diplomatic Shipment') {
                        pageURL = '/apex/rateReplyDSdiplomat';
                } else if (rr.RecordType.Name == 'DS FCL') {
                        pageURL = '/apex/rateReplyDSFCL';
                } else if (rr.RecordType.Name == 'DS LCL') {
                        pageURL = '/apex/rateReplyDSlcl';
                }
                else if (rr.RecordType.Name == 'Origin Service') {
                        pageURL = '/apex/rateReplyOS';
                }
                PageReference pdfPage = new PageReference(pageURL);
                
                /* Set rate reply ID on page defintion */
                pdfPage.getParameters().put('id', rr.id);
                
                /* Generate PDF Blob */
                Blob pdfBlob;
                if(!test.isRunningTest()){ // Date: 1/14/2016:- for skipping in this code in Test Class because it was throwing error of Method donot support getContent
					pdfBlob = pdfPage.getContent();
				}else{
					pdfBlob = blob.valueof('TEST');
				}
                //Blob pdfBlob = pdfPage.getContent();
                
                /* Convert PDF as attachment in Internal Costing object */
                Attachment a = new Attachment(parentId = rr.id, 
                name = 'Rate Reply - ' + rr.Quote_Reference2__c + '.pdf', body = pdfBlob);
                        
                /* insert attachment to object */
                insert a;
                
                /* Redirect to display PDF page */
                pdfPage.setRedirect(true);
                return pdfPage;
        }
        static testMethod void t1() {
                Account a = new Account(name='Tan Enterprise');
        insert a;
        Contact c = new Contact(firstName='Ken', lastName='LIM', accountid=A.id, Email='lim@myMail.com');
        insert c;
                          
        Rate_Reply__c r = new Rate_Reply__c (recordtypeid = '01220000000TsdvAAC', Agent_Name__c = c.Id,
        Agent_Email__c = 'agent@what.com', Quote_Validity_days__c = '60', Initials__c = 'LLY',
        Date__c = Date.newInstance(2009, 11, 01), Currency__c = 'USD');
        insert r;
        
                rateReplyAttach rra = new rateReplyAttach ( new ApexPages.StandardController(r) );
        }
        public static testMethod void test1() {
                Account a = new Account(name='Tan Enterprise');
        insert a;
        Contact c = new Contact(firstName='Ken', lastName='LIM', accountid=A.id, Email='lim@myMail.com');
        insert c;
                          
        Rate_Reply__c r = new Rate_Reply__c (recordtypeid = '01220000000TsdvAAC', Agent_Name__c = c.Id,
        Agent_Email__c = 'agent@what.com', Quote_Validity_days__c = '60', Initials__c = 'LLY',
        Date__c = Date.newInstance(2009, 11, 01), Currency__c = 'USD');
        insert r;
                
                PageReference pageRef = new PageReference('/apex/rateReplyDS');
        Test.setCurrentPage(pageRef);
        system.debug( '****************************** rate reply id is '+ r.id);
        
        ApexPages.currentPage().getParameters().put('id', r.id);
        
                rateReplyAttach rra = new rateReplyAttach ();
                try { rra.attachQuote(); } catch( System.NullPointerException npe) { } 
        }
}