2nd training/Community/Community/Community1/force-app/main/default/objects/Account/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <description>Overseas trading partners that reciprocrates tonnage with us.</description>
    <label>Agent</label>
</RecordType>

2nd training/Community/Community/Community1/force-app/main/default/objects/Account/recordTypes/Artmove.recordType-meta.xml
<RecordType>
    <fullName>Artmove</fullName>
    <active>true</active>
    <description>Artmove accounts.</description>
    <label>Artmove</label>
</RecordType>

2nd training/Community/Community/Community1/force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

2nd training/Community/Community/Community1/force-app/main/default/objects/Contact/recordTypes/Agent.recordType-meta.xml
<RecordType>
    <fullName>Agent</fullName>
    <active>true</active>
    <description>Overseas trading partners (agents) that reciprocrates tonnage with us</description>
    <label>Agent</label>
</RecordType>

2nd training/Community/Community/Community1/force-app/main/default/objects/Contact/recordTypes/Artmove.recordType-meta.xml
<RecordType>
    <fullName>Artmove</fullName>
    <active>true</active>
    <label>Artmove</label>
</RecordType>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/Rate_Reply__c.object-meta.xml
<CustomObject>
    <description>Inbound rate reply</description>
    <label>Rate Reply</label>
    <nameField>
        <displayFormat>RR/{YY}/{MM}/{0000}</displayFormat>
        <label>Rate Reply ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Replies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Agent_Email__c.field-meta.xml
<CustomField>
    <fullName>Agent_Email__c</fullName>
    <defaultValue>&quot;Do not enter anything&quot;</defaultValue>
    <label>Agent Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of agent requesting rates</description>
    <inlineHelpText>Name of agent requesting rates</inlineHelpText>
    <label>Agent Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rate Reply</relationshipLabel>
    <relationshipName>R00N2000000121wnEAA</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Date of quotation</description>
    <inlineHelpText>Date of quotation</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Initials__c.field-meta.xml
<CustomField>
    <fullName>Initials__c</fullName>
    <label>Initials</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/quote_number__c.field-meta.xml
<CustomField>
    <fullName>quote_number__c</fullName>
    <externalId>true</externalId>
    <label>quote number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Quote_Revision__c.field-meta.xml
<CustomField>
    <fullName>Quote_Revision__c</fullName>
    <inlineHelpText>Indicate the number of times the quotation is revised</inlineHelpText>
    <label>Quote Revision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Rate_Reply__c/fields/Quote_Validity_days__c.field-meta.xml
<CustomField>
    <fullName>Quote_Validity_days__c</fullName>
    <defaultValue>&quot;60&quot;</defaultValue>
    <description>Number of days quote is valid</description>
    <inlineHelpText>Number of days quote is valid</inlineHelpText>
    <label>Quote Validity (days)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/Traffic__c.object-meta.xml
<CustomObject>
    <description>Custom Object for Traffic Department</description>
    <label>Traffic</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Traffic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Traffic</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Billing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Billing_Instructions__c</fullName>
    <description>Hidden field for billing instructions in Way Bill (Traffic Object)</description>
    <label>Billing Instructions</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Shipment_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>You are to bill all destination charges to:</fullName>
            </value>
            <value>
                <fullName>You are to bill us according to your quote of:</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Container_Type__c.field-meta.xml
<CustomField>
    <fullName>Container_Type__c</fullName>
    <label>Container Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CASE</fullName>
            </value>
            <value>
                <fullName>CRATE</fullName>
            </value>
            <value>
                <fullName>LIFTVAN</fullName>
            </value>
            <value>
                <fullName>20&apos; CONTAINER</fullName>
            </value>
            <value>
                <fullName>40&apos; CONTAINER</fullName>
            </value>
            <value>
                <fullName>40&apos; HIGH CUBE CONTAINER</fullName>
            </value>
            <value>
                <fullName>45&apos; HC</fullName>
            </value>
            <value>
                <fullName>TRIWALL</fullName>
            </value>
            <value>
                <fullName>CASES</fullName>
            </value>
            <value>
                <fullName>LIFTVANS</fullName>
            </value>
            <value>
                <fullName>LOOSE PACKAGES</fullName>
            </value>
            <value>
                <fullName>PALLET</fullName>
            </value>
            <value>
                <fullName>PALLETS</fullName>
            </value>
            <value>
                <fullName>LOOSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <defaultValue>&quot;OF USED PERSONAL EFFECTS&quot; &amp; BR() &amp;
&quot;&amp; HOUSEHOLD GOODS&quot;</defaultValue>
    <label>Content</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/ETA__c.field-meta.xml
<CustomField>
    <fullName>ETA__c</fullName>
    <formula>Opportunity_Name__r.ETA_String__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ETA</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/ETD__c.field-meta.xml
<CustomField>
    <fullName>ETD__c</fullName>
    <formula>Opportunity_Name__r.ETD_String__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ETD</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Gross_Weight_2_KG__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_2_KG__c</fullName>
    <label>Gross Weight 2 (KG)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Gross_Weight_KG__c.field-meta.xml
<CustomField>
    <fullName>Gross_Weight_KG__c</fullName>
    <label>Gross Weight (KG)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Load_1__c.field-meta.xml
<CustomField>
    <fullName>Load_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Load 1</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Load_2__c.field-meta.xml
<CustomField>
    <fullName>Load_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Load 2</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Packages_2__c.field-meta.xml
<CustomField>
    <fullName>Packages_2__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Packages 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Packages__c.field-meta.xml
<CustomField>
    <fullName>Packages__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of packages in a container load</description>
    <label>Packages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Quantity_of_Container_2__c.field-meta.xml
<CustomField>
    <fullName>Quantity_of_Container_2__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity of Container 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Quantity_of_Containers__c.field-meta.xml
<CustomField>
    <fullName>Quantity_of_Containers__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity of Containers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Shipping_Line_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Line_Carrier__c</fullName>
    <label>Shipping Line / Carrier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Shipping_Mode__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Mode__c</fullName>
    <label>Shipping Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BY SEA</fullName>
            </value>
            <value>
                <fullName>BY AIR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Special_Instruction_Details__c.field-meta.xml
<CustomField>
    <fullName>Special_Instruction_Details__c</fullName>
    <label>Special Instruction Details</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Shipment_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Door to Door shipment, please contact shippers for immediate clearance and delivery. Helutrans will not be responsible for any storage charges.</fullName>
                <default>true</default>
                <label>Door to Door shipment, please contact shippers for immediate clearance and delivery. Helutrans will not be responsible for any storage charges.</label>
            </value>
            <value>
                <fullName>Door to Port shipment, please contact shippers for immediate clearance. Helutrans will not be responsible for any storage charges.</fullName>
            </value>
            <value>
                <fullName>Door to Door shipment, please contact shippers for immediate clearance and delivery. Helutrans will not be responsible for any charges and delivery incurred at destination.</fullName>
            </value>
            <value>
                <fullName>Door to Port shipment, please contact shippers for immediate clearance. Helutrans will not be responsible for any charges incurred at destination.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Volume_2_CBM__c.field-meta.xml
<CustomField>
    <fullName>Volume_2_CBM__c</fullName>
    <label>Volume 2 (CBM)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Traffic__c/fields/Volume_CBM__c.field-meta.xml
<CustomField>
    <fullName>Volume_CBM__c</fullName>
    <label>Volume (CBM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/TestTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestTrigger {

    static testMethod void myUnitTest() {
        list<Opportunity> opp2Insert = new list<Opportunity>();
        /* Create new Account and Contact record */
        Account a = new Account(name='Tan Enterprise');
        insert a;
        Contact c = new Contact(firstName='Ken', lastName='LEE', 
        accountid=A.id, Email='lim@myMail.com', Phone='777', MobilePhone='111', Fax='222');
        insert c;
        
        /* Create new INBOUND Opportunity record */
        Opportunity opp = new Opportunity 
        (recordtypeid = '012200000008avZAAQ', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD');
        //insert opp;
        opp2Insert.add(opp);
        Opportunity opp2 = new Opportunity 
        (recordtypeid = '012200000008avZAAQ', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'USD');
        //insert opp2; 
        opp2Insert.add(opp2);
        Opportunity opp3 = new Opportunity 
        (recordtypeid = '012200000008avZAAQ', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'EUR');
        //insert opp3; 
        opp2Insert.add(opp3);
        System.assert(opp.recordtypeid == '012200000008avZAAQ');
        
        /* Create new OUTBOUND Opportunity record */
        Opportunity opp4 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 01, 29), ETD__c = Date.newInstance(2010, 01, 20));
        //insert opp4;
        opp2Insert.add(opp4);
        Opportunity opp5 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 02, 29), ETD__c = Date.newInstance(2010, 02, 20));
        //insert opp5;
        opp2Insert.add(opp5);
        Opportunity opp6 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 03, 29), ETD__c = Date.newInstance(2010, 03, 20));
        //insert opp6;
        opp2Insert.add(opp6);
        Opportunity opp7 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 04, 29), ETD__c = Date.newInstance(2010, 04, 20));
        //insert opp7;
        opp2Insert.add(opp7);
        Opportunity opp8 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 05, 29), ETD__c = Date.newInstance(2010, 05, 20));
        //insert opp8;
        opp2Insert.add(opp8);
        Opportunity opp9 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 06, 29), ETD__c = Date.newInstance(2010, 06, 20));
        //insert opp9;
        opp2Insert.add(opp9);
        Opportunity opp10 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 07, 29), ETD__c = Date.newInstance(2010, 07, 20));
        //insert opp10;
        opp2Insert.add(opp10);
        Opportunity opp11 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 08, 29), ETD__c = Date.newInstance(2010, 08, 20));
        //insert opp11;
        opp2Insert.add(opp11);
        Opportunity opp12 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 09, 29), ETD__c = Date.newInstance(2010, 09, 20));
        //insert opp12;
        opp2Insert.add(opp12);
        Opportunity opp13 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 10, 29), ETD__c = Date.newInstance(2010, 10, 20));
        //insert opp13;
        opp2Insert.add(opp13);
        Opportunity opp14 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 11, 29), ETD__c = Date.newInstance(2010, 11, 20));
        //insert opp14;
        opp2Insert.add(opp14);
        Opportunity opp15 = new Opportunity 
        (recordtypeid = '01220000000Tr5FAAS', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test Opportunity', StageName = 'Survey', Billing_Currency__c = 'SGD', 
        ETA__c = Date.newInstance(2011, 12, 29), ETD__c = Date.newInstance(2010, 12, 20));
        //insert opp15;
        opp2Insert.add(opp15);
        /* Create new ARTMOVE Opportunity record */
        Opportunity opp16 = new Opportunity 
        (recordtypeid = '012200000008bhJ', AM_Job_Type__c = 'AC - Crating Services', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test ARTMOVE Opportunity', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp16;
        opp2Insert.add(opp16);
        
        /* Create new ARTMOVE FP */
        Opportunity opp17 = new Opportunity 
        (recordtypeid = '01220000000JTCx', AM_Job_Type__c = 'IM - International Move', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test ARTMOVE Opportunity 2', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp17;
        opp2Insert.add(opp17);
        /* Create new ARTMOVE HK */
        Opportunity opp18 = new Opportunity 
        (recordtypeid = '01220000000JTD7', AM_Job_Type__c = 'AS - Installation', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test ARTMOVE Opportunity 2', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp18;
        opp2Insert.add(opp18);
        /* Create new ARTMOVE SH */
        Opportunity opp19 = new Opportunity 
        (recordtypeid = '01220000000JTD2', AM_Job_Type__c = 'AX - Anything & Everything', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test ARTMOVE Opportunity 2', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp19;
        opp2Insert.add(opp19);
        /* Create new ARTMOVE BJ ZAI*/
        Opportunity opp20 = new Opportunity 
        (recordtypeid = '01220000000JTDC', AM_Job_Type__c = 'DS - Destination Services', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test ARTMOVE Opportunity 2', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp20;
        opp2Insert.add(opp20);
        /* Create new HHG IM Agent Booked door to door*/
        Opportunity opp21 = new Opportunity 
        (recordtypeid = '01220000000Tr5A', Shipment_Details__c = 'IM Door to Door', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test HHG IM Agent Booked', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp21;
        opp2Insert.add(opp21);
        /* Create new HHG LM Corporate Account local move*/
        Opportunity opp22 = new Opportunity 
        (recordtypeid = '01220000000Tr5K', Shipment_Details__c = 'Local Move', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test HHG IM Agent Booked', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp22;
        opp2Insert.add(opp22);
        /* Create new HHG WA Personal Account warehouse*/
        Opportunity opp23 = new Opportunity 
        (recordtypeid = '01220000000Tr5F', Shipment_Details__c = 'Warehousing', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test HHG IM Agent Booked', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp23;
        opp2Insert.add(opp23);
        /* Create new HHG WA Personal Account Origin Services*/
        Opportunity opp24 = new Opportunity 
        (recordtypeid = '01220000000Tr5F', Shipment_Details__c = 'Origin Services', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test HHG Origin Services', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp24;
        opp2Insert.add(opp24);
        /* Create new HHG WA Personal Account Office Move*/
        Opportunity opp25 = new Opportunity 
        (recordtypeid = '01220000000Tr5F', Shipment_Details__c = 'Office Move', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test HHG Office Move', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp25;
        opp2Insert.add(opp25);
        /* Create new HHG IM Agent Booked door to port*/
        Opportunity opp26 = new Opportunity 
        (recordtypeid = '01220000000Tr5A', Shipment_Details__c = 'IM Door to Port', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2012, 11, 01), 
        Name = 'Test HHG IM Agent Booked', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp26;       
        opp2Insert.add(opp26);
        
        /* Create new HHG IM Agent Booked 3rd Country Move*/
        Opportunity opp27 = new Opportunity 
        (recordtypeid = '01220000000Tr5A', Shipment_Details__c = '3rd Country Move', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2012, 11, 02), 
        Name = 'Test HHG IM Agent Booked3', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp27;
        opp2Insert.add(opp27);
        /* Create new HHG IM Agent Booked IM DTD Inbound*/
        Opportunity opp28 = new Opportunity 
        (recordtypeid = '01220000000Tr5A', Shipment_Details__c = 'IM DTD Inbound', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2012, 11, 02), 
        Name = 'Test HHG IM Agent Booked5', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp28;
        opp2Insert.add(opp28);
        /* Create new HHG Quote*/
        Opportunity opp32 = new Opportunity 
        (recordtypeid = '01220000000Tr5F', Shipment_Details__c = 'Office Move', 
        LeadSource ='Agent Rate Request', Quote_Mode__c ='IM', CloseDate = Date.newInstance(2012, 11, 01), 
        Name = 'Test HHG Office Move', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp32;
        opp2Insert.add(opp32);
        Opportunity opp29 = new Opportunity 
        (recordtypeid = '012200000008bhJAAQ', AM_Job_Type__c = 'IT - Third Party Managament', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test ARTMOVE Opportunity 2', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp29;
        opp2Insert.add(opp29);
        Opportunity opp30 = new Opportunity 
        (recordtypeid = '012200000008bhJAAQ', AM_Job_Type__c = 'LS - Local Services', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test ARTMOVE Opportunity 2', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp30;
        opp2Insert.add(opp30);
        Opportunity opp31 = new Opportunity 
        (recordtypeid = '012200000008bhJAAQ', AM_Job_Type__c = 'MP - Manpower', 
        LeadSource ='Agent Rate Request', CloseDate = Date.newInstance(2009, 11, 01), 
        Name = 'Test ARTMOVE Opportunity 2', StageName = 'Survey', Person_In_Charge__c = 'IN');
        //insert opp31;
        opp2Insert.add(opp31);
        insert opp2Insert;
        /* Create new DS Rate Reply record */              
        list<Rate_Reply__c> rr2Insert = new list<Rate_Reply__c>();
        Rate_Reply__c r3 = new Rate_Reply__c (recordtypeid = '01220000000TsdvAAC', Agent_Name__c = c.Id,
        Agent_Email__c = 'OSagent@what.com', Quote_Validity_days__c = '60', Initials__c = 'LLY',
        Date__c = Date.newInstance(2009, 11, 17), Quote_Revision__c = 'A', quote_number__c = 'quote');
        insert r3;
        
        r3.Agent_Email__c = 'OSagent@mail.com';
        update r3;
        
        Rate_Reply__c r4 = new Rate_Reply__c (recordtypeid = '01220000000TsdvAAC', Agent_Name__c = c.Id,
        Agent_Email__c = 'OSagent@what.com', Quote_Validity_days__c = '60', Initials__c = 'LLY',
        Date__c = Date.newInstance(2009, 11, 17), Quote_Revision__c = 'A', quote_number__c = 'quote-');
        insert r4;
        
        r4.Agent_Email__c = 'OSagent@mail.com';
        update r4;
        
        /* Create new OS Rate Reply record */
        Rate_Reply__c r2 = new Rate_Reply__c (recordtypeid = '01220000000Tse0AAC', Agent_Name__c = c.Id,
        Agent_Email__c = 'OSagent@what.com', Quote_Validity_days__c = '60', Initials__c = 'LLY',
        Date__c = Date.newInstance(2009, 11, 01), Quote_Revision__c = 'A', quote_number__c = 'quote');
        insert r2;
        
        r2.Agent_Email__c = 'OSagent@mail.com';
        update r2;
        
        Rate_Reply__c r5 = new Rate_Reply__c (recordtypeid = '01220000000Tse0AAC', Agent_Name__c = c.Id,
        Agent_Email__c = 'OSagent@what.com', Quote_Validity_days__c = '60', Initials__c = 'LLY',
        Date__c = Date.newInstance(2009, 11, 17), Quote_Revision__c = 'A', quote_number__c = 'quote-');
        insert r5;
        
        r5.Agent_Email__c = 'OSagent@mail.com';
        update r5;
        
        /* Create new OpportunityContactRole record */
        OpportunityContactRole ocrr = new OpportunityContactRole (OpportunityId = opp4.id, ContactId = c.id, Role = 'Shipper');
        insert ocrr;
        OpportunityContactRole ocrr2 = new OpportunityContactRole (OpportunityId = opp4.id, ContactId = c.id, Role = 'Destination Agent');
        insert ocrr2;
        OpportunityContactRole ocrr3 = new OpportunityContactRole (OpportunityId = opp4.id, ContactId = c.id, Role = 'Booker');
        insert ocrr3;
        
        /* Update OUTBOUND Opportunity record 
        opp4.Name = 'NEW opp';
        update opp4;
        opp5.Name = 'NEW opp';
        update opp5;
        opp6.Name = 'NEW opp';
        update opp6;
        opp7.Name = 'NEW opp';
        update opp7;
        opp8.Name = 'NEW opp';
        update opp8;
        opp9.Name = 'NEW opp';
        update opp9;
        opp10.Name = 'NEW opp';
        update opp10;
        opp11.Name = 'NEW opp';
        update opp11;
        opp12.Name = 'NEW opp';
        update opp12;
        opp13.Name = 'NEW opp';
        update opp13;
        opp14.Name = 'NEW opp';
        update opp14;
        opp15.Name = 'NEW opp';
        update opp15;
        */
        
        /* Create new Traffic record */
        Traffic__c t = new Traffic__c (Load_1__c = true, Load_2__c = false, Shipping_Mode__c = 'BY SEA', 
        Billing_Instructions__c = 'You are to bill us according to your quote of:', 
        Quantity_of_Containers__c = 100, Container_Type__c = 'CASE', Gross_Weight_KG__c = 1000, Volume_CBM__c = 500,
        Packages__c = 30, Content__c = 'Content text',
        Special_Instruction_Details__c = 'Door to Port shipment, please contact shippers for immediate clearance. Helutrans will not be responsible for any storage charges.');
        insert t;
        
        Traffic__c t2 = new Traffic__c (Load_1__c = true, Load_2__c = true, Shipping_Mode__c = 'BY SEA', 
        Billing_Instructions__c = 'You are to bill us according to your quote of:', 
        Quantity_of_Containers__c = 100, Quantity_of_Container_2__c = 40, Container_Type__c = 'CASE', 
        Gross_Weight_KG__c = 1000, Gross_Weight_2_KG__c = 800, Volume_CBM__c = 500, Volume_2_CBM__c = 200,
        Packages__c = 30, Packages_2__c = 10, Content__c = 'Content text',
        Special_Instruction_Details__c = 'Door to Port shipment, please contact shippers for immediate clearance. Helutrans will not be responsible for any storage charges.');
        insert t2;
        
        /* Update Traffic record */
        t.Shipping_Line_Carrier__c = 'my shipping line';
        update t;

    }//end of my unit test
}