2nd training/Community/Community/Community1/force-app/main/default/objects/Costing_Sheet__c/Costing_Sheet__c.object-meta.xml
<CustomObject>
    <label>Costing Sheet</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Costing Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costing Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Costing_Sheet__c/fields/Costing_Sheet_Id__c.field-meta.xml
<CustomField>
    <fullName>Costing_Sheet_Id__c</fullName>
    <label>Costing Sheet Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Costing_Sheet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Costing Sheets</relationshipLabel>
    <relationshipName>Costing_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/Crate__c.object-meta.xml
<CustomObject>
    <description>Holds Collector Crate information</description>
    <label>Crate</label>
    <nameField>
        <label>Crate ID (barcode)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Date_In__c.field-meta.xml
<CustomField>
    <fullName>Date_In__c</fullName>
    <label>Date In</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Job_Reference__c.field-meta.xml
<CustomField>
    <fullName>Job_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Reference</label>
    <referenceTo>Job_Reference__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crate Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/myCollector__c.field-meta.xml
<CustomField>
    <fullName>myCollector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collector</label>
    <referenceTo>artApp__Collector__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/Job_Reference__c.object-meta.xml
<CustomObject>
    <description>Stores the Job reference no</description>
    <label>Job Reference</label>
    <nameField>
        <label>Job Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Job References</relationshipLabel>
    <relationshipName>Job_References</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Arpan-PersonalOrg/force-app/main/default/classes/QrCodeScannerControllerTest.cls
@isTest
public class QrCodeScannerControllerTest {
    @isTest
    public static void testRun1(){
        Opportunity newOppty = new Opportunity();
        newOppty.StageName = 'Prospecting';
        newOppty.Name = 'Test Oppty';
        newOppty.CloseDate = system.today();
        newOppty.Estimated_Volume__c = 10;
        newOppty.Pack_Date_1__c = system.today();
        newOppty.Amount = 100;
        insert newOppty; 
        
       /* Costing_Sheet__c newCostingSheet = new Costing_Sheet__c();
        newCostingSheet.Costing_Sheet_Id__c ='abc';
        newCostingSheet.Opportunity__c = newOppty.id;
        insert newCostingSheet;*/
        
        newOppty.StageName = 'Closed Won';
      //  newOppty.Approved_Costing_Sheet__c = newCostingSheet.id;
        update newOppty;

        
        Job_Reference__c newJobReference = new Job_Reference__c();
        newJobReference.Name = 'New Job Reference';
        newJobReference.Opportunity__c =  newOppty.id;
        insert newJobReference;
        artApp__Collector__c newCollector = new artApp__Collector__c();
        newCollector.Name = 'New Collector';
        insert newCollector; 
        
        artApp__Artist__c newArtist = new artApp__Artist__c();
        newArtist.Name = 'New Artist';
        insert newArtist;
        Crate__c sampleCrate = new Crate__c();
        sampleCrate.Name = 'Sample Crate';
        sampleCrate.Date_In__c = Date.today();
        sampleCrate.Height__c = 10;
        sampleCrate.Width__c = 10;
        sampleCrate.Length__c = 10;
        sampleCrate.Job_Reference__c = newJobReference.id;
        sampleCrate.myCollector__c = newCollector.id;
        insert sampleCrate;
        artApp__Artwork__c newArtWork = new artApp__Artwork__c();
        newArtWork.Name = 'Sample Artwork';
        newArtWork.artApp__Artist__c = newArtist.id;
        newArtWork.Crate__c = sampleCrate.id; 
        insert newArtWork;
        
        PageReference pageRef = Page.QrCodeScanner;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id',sampleCrate.id);
        QrCodeScannerController inst = new QrCodeScannerController();
    }
     @isTest
    public static void testRun2(){
        Opportunity newOppty = new Opportunity();
        newOppty.StageName = 'Prospecting';
        newOppty.Name = 'Test Oppty';
        newOppty.CloseDate = system.today();
        newOppty.Estimated_Volume__c = 10;
        newOppty.Pack_Date_1__c = system.today();
        newOppty.Amount = 100;
        insert newOppty; 
        
        /* Costing_Sheet__c newCostingSheet = new Costing_Sheet__c();
        newCostingSheet.Costing_Sheet_Id__c ='abc';
        newCostingSheet.Opportunity__c = newOppty.id;
        insert newCostingSheet;*/
        
        newOppty.StageName = 'Closed Won';
      //  newOppty.Approved_Costing_Sheet__c = newCostingSheet.id;
        update newOppty;

        
        Job_Reference__c newJobReference = new Job_Reference__c();
        newJobReference.Name = 'New Job Reference';
        newJobReference.Opportunity__c =  newOppty.id;
        insert newJobReference;
        artApp__Collector__c newCollector = new artApp__Collector__c();
        newCollector.Name = 'New Collector';
        insert newCollector; 
        
        artApp__Artist__c newArtist = new artApp__Artist__c();
        newArtist.Name = 'New Artist';
        insert newArtist;
        
        Location__c newLocation = new Location__c();
        newLocation.Name = 'ATL-E1';
        insert newLocation; 
        
        Crate__c sampleCrate = new Crate__c();
        sampleCrate.Name = 'Sample Crate';
        sampleCrate.Location__c = newLocation.id;
        sampleCrate.Date_In__c = Date.today();
        sampleCrate.Height__c = 10;
        sampleCrate.Width__c = 10;
        sampleCrate.Length__c = 10;
        sampleCrate.Job_Reference__c = newJobReference.id;
        sampleCrate.myCollector__c = newCollector.id;
        insert sampleCrate;
        artApp__Artwork__c newArtWork = new artApp__Artwork__c();
        newArtWork.Name = 'Sample Artwork';
        newArtWork.artApp__Artist__c = newArtist.id;
        newArtWork.Crate__c = sampleCrate.id; 
        insert newArtWork;
        
        PageReference pageRef = Page.QrCodeScanner;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id',sampleCrate.id);
        QrCodeScannerController inst = new QrCodeScannerController();
    }
     @isTest
    public static void testRun3(){
        Opportunity newOppty = new Opportunity();
        newOppty.StageName = 'Prospecting';
        newOppty.Name = 'Test Oppty';
        newOppty.CloseDate = system.today();
        newOppty.Estimated_Volume__c = 10;
        newOppty.Pack_Date_1__c = system.today();
        newOppty.Amount = 100;
        insert newOppty; 
        
        /* Costing_Sheet__c newCostingSheet = new Costing_Sheet__c();
        newCostingSheet.Costing_Sheet_Id__c ='abc';
        newCostingSheet.Opportunity__c = newOppty.id;
        insert newCostingSheet;*/
        
        newOppty.StageName = 'Closed Won';
      //  newOppty.Approved_Costing_Sheet__c = newCostingSheet.id;
        update newOppty;

        
        Job_Reference__c newJobReference = new Job_Reference__c();
        newJobReference.Name = 'New Job Reference';
        newJobReference.Opportunity__c =  newOppty.id;
        insert newJobReference;
        artApp__Collector__c newCollector = new artApp__Collector__c();
        newCollector.Name = 'New Collector';
        insert newCollector; 
        
        artApp__Artist__c newArtist = new artApp__Artist__c();
        newArtist.Name = 'New Artist';
        insert newArtist;
        
        Location__c newLocation = new Location__c();
        newLocation.Name = 'Released ATL-E1';
        insert newLocation; 
        
        Crate__c sampleCrate = new Crate__c();
        sampleCrate.Name = 'Sample Crate';
        sampleCrate.Location__c = newLocation.id;
        sampleCrate.Date_In__c = Date.today();
        sampleCrate.Height__c = 10;
        sampleCrate.Width__c = 10;
        sampleCrate.Length__c = 10;
        sampleCrate.Job_Reference__c = newJobReference.id;
        sampleCrate.myCollector__c = newCollector.id;
        insert sampleCrate;
        artApp__Artwork__c newArtWork = new artApp__Artwork__c();
        newArtWork.Name = 'Sample Artwork';
        newArtWork.artApp__Artist__c = newArtist.id;
        newArtWork.Crate__c = sampleCrate.id; 
        insert newArtWork;
        
        PageReference pageRef = Page.QrCodeScanner;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id',sampleCrate.id);
        QrCodeScannerController inst = new QrCodeScannerController();
    }
     @isTest
    public static void testRun4(){
        PageReference pageRef = Page.QrCodeScanner;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id','');
        QrCodeScannerController inst = new QrCodeScannerController();
    }
}