2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/Job_Reference__c.object-meta.xml
<CustomObject>
    <description>Stores the Job reference no</description>
    <label>Job Reference</label>
    <nameField>
        <label>Job Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/API_Error__c.field-meta.xml
<CustomField>
    <fullName>API_Error__c</fullName>
    <label>API Error</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Ultimate owner of the items.</inlineHelpText>
    <label>Collector</label>
    <referenceTo>artApp__Collector__c</referenceTo>
    <relationshipLabel>Job References</relationshipLabel>
    <relationshipName>Job_References</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/ExhibitionN__c.field-meta.xml
<CustomField>
    <fullName>ExhibitionN__c</fullName>
    <formula>Opportunity__r.Exhibition__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exhibition</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Job References</relationshipLabel>
    <relationshipName>Job_References</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Push_Job_Info__c.field-meta.xml
<CustomField>
    <fullName>Push_Job_Info__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pushed JobReference Info</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Job</fullName>
                <default>true</default>
                <label>New Job</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/PushJobReferenceToEportalController.cls
public class PushJobReferenceToEportalController {
    @auraEnabled
    public static String apiPushInfo(ID recordId){
        string message = '';
        try{
            list<Job_Reference__c> joblst = [SELECT Id,Opportunity__c,Client_Account__c,Opportunity__r.Push_Opportunity_Info__c,Status__c,
                                             Name,ExhibitionN__c,Push_Job_Info__c,Opportunity__r.Approved_Costing_Sheet__c,Opportunity__r.Approved_Costing_Sheet__r.Costing_Sheet_Id__c,Opportunity__r.Approved_Costing_Sheet__r.Revision_ID__c from Job_Reference__c where Id=:recordId];
            if(joblst!=null && joblst.size() > 0){
                if(joblst[0].Push_Job_Info__c)
                    message = 'Warning@Job Reference is already pushed to EPortal';
                else if(joblst[0].Opportunity__c==null || !(joblst[0].Opportunity__r.Push_Opportunity_Info__c))
                    message = 'Warning@Please push the linked Opportunity to portal first.';
                else If(joblst[0].Opportunity__c!=null && (joblst[0].Opportunity__r.Approved_Costing_Sheet__c==null || joblst[0].Opportunity__r.Approved_Costing_Sheet__r.Costing_Sheet_Id__c==null)){
                 	message = 'Warning@Please select the Approved Costing Sheet on the Opportunity before pushing the Job reference to portal.';   
                }else{
                    Job_Reference__c job = PortalAPIUtility.pushJobReference(joblst);
                    if(job.API_Error__c!=null)
                        message = 'Error@'+job.API_Error__c;
                    else
                        message = 'success@Data Pushed Successfully';
                }
            }else
                message+= 'Warning@Job Reference list is Empty';
        }catch(Exception e){
            message='Error@'+e.getMessage();
        }
        return message;
    }
}