2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/Job_Reference__c.object-meta.xml
<CustomObject>
    <description>Stores the Job reference no</description>
    <label>Job Reference</label>
    <nameField>
        <label>Job Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Ultimate owner of the items.</inlineHelpText>
    <label>Collector</label>
    <referenceTo>artApp__Collector__c</referenceTo>
    <relationshipLabel>Job References</relationshipLabel>
    <relationshipName>Job_References</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/ExhibitionN__c.field-meta.xml
<CustomField>
    <fullName>ExhibitionN__c</fullName>
    <formula>Opportunity__r.Exhibition__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exhibition</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Job References</relationshipLabel>
    <relationshipName>Job_References</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Push_Job_Info__c.field-meta.xml
<CustomField>
    <fullName>Push_Job_Info__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pushed JobReference Info</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Job</fullName>
                <default>true</default>
                <label>New Job</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/classes/pushJobReferenceToEportalBatch.cls
global class pushJobReferenceToEportalBatch implements Database.Batchable<sObject>,Database.AllowsCallouts{
   set<Id> JobIdSet;
    global pushJobReferenceToEportalBatch(set<ID> jobSet) {
        JobIdSet = jobSet;
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id,Opportunity__c,Opportunity__r.Push_Opportunity_Info__c,Name,Status__c,Client_Account__c,ExhibitionN__c,Push_Job_Info__c,Opportunity__r.Approved_Costing_Sheet__c,Opportunity__r.Approved_Costing_Sheet__r.Costing_Sheet_Id__c,Opportunity__r.Approved_Costing_Sheet__r.Revision_ID__c from Job_Reference__c where Id IN:JobIdSet]);
    }
    global void execute(Database.BatchableContext BC, List<Job_Reference__c> jbReflst) {
        PortalAPIUtility.pushJobReference(jbReflst);
    }
    global void finish(Database.BatchableContext BC) {
        
    }
}