2nd training/Community/Community/Community1/force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset management</description>
    <label>Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Asset__c/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Station</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Asset__c/fields/HT_Barcode_No__c.field-meta.xml
<CustomField>
    <fullName>HT_Barcode_No__c</fullName>
    <label>HT Barcode No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Asset__c/fields/Loaned_To__c.field-meta.xml
<CustomField>
    <fullName>Loaned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact Lookup</description>
    <label>Loaned To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Asset__c/fields/Location_New__c.field-meta.xml
<CustomField>
    <fullName>Location_New__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Asset__c/fields/Location_User__c.field-meta.xml
<CustomField>
    <fullName>Location_User__c</fullName>
    <label>Location/User</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Asset__c/fields/Serial_No__c.field-meta.xml
<CustomField>
    <fullName>Serial_No__c</fullName>
    <label>Serial No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Asset__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Equipment</fullName>
            </value>
            <value>
                <fullName>Expendable</fullName>
            </value>
            <value>
                <fullName>HVAC</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Contact/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Contact/fields/Gender_HT__c.field-meta.xml
<CustomField>
    <fullName>Gender_HT__c</fullName>
    <label>Gender:</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Contact/fields/ID_No_HT__c.field-meta.xml
<CustomField>
    <fullName>ID_No_HT__c</fullName>
    <label>ID No:</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Contact/fields/ID_Type_HT__c.field-meta.xml
<CustomField>
    <fullName>ID_Type_HT__c</fullName>
    <label>ID Type:</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NRIC (Pink)</fullName>
            </value>
            <value>
                <fullName>NRIC (Blue)</fullName>
            </value>
            <value>
                <fullName>FIN</fullName>
            </value>
            <value>
                <fullName>HKID</fullName>
            </value>
            <value>
                <fullName>RIC (China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>TPR</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Boss</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>IML</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Art Exhibition</fullName>
            </value>
            <value>
                <fullName>Auction House</fullName>
            </value>
            <value>
                <fullName>Gallery</fullName>
            </value>
            <value>
                <fullName>Instituition</fullName>
            </value>
            <value>
                <fullName>Private Collector</fullName>
            </value>
            <value>
                <fullName>Museum</fullName>
            </value>
            <value>
                <fullName>IEA contacts</fullName>
            </value>
            <value>
                <fullName>Secretary</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/fields/Storage_Facility__c.field-meta.xml
<CustomField>
    <fullName>Storage_Facility__c</fullName>
    <label>Storage Facility</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>* Not in Storage</fullName>
            </value>
            <value>
                <fullName>ATL, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Cheung Hing Shing, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Chun Sing, Hong Kong</fullName>
            </value>
            <value>
                <fullName>CITIC, Hong Kong</fullName>
            </value>
            <value>
                <fullName>CityCentre Storage, Singapore</fullName>
            </value>
            <value>
                <fullName>Display Site</fullName>
            </value>
            <value>
                <fullName>Gehua</fullName>
            </value>
            <value>
                <fullName>Global Gateway, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hellmann, Hong Kong</fullName>
            </value>
            <value>
                <fullName>HKCEC</fullName>
            </value>
            <value>
                <fullName>In Passage</fullName>
            </value>
            <value>
                <fullName>Jaguar, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Jin Ma Building, Beijing</fullName>
            </value>
            <value>
                <fullName>Kong Nam, Hong Kong</fullName>
            </value>
            <value>
                <fullName>LinJi Building, Beijing</fullName>
            </value>
            <value>
                <fullName>Mapletree, Hong Kong</fullName>
            </value>
            <value>
                <fullName>MBS</fullName>
            </value>
            <value>
                <fullName>Richwealth, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Shanghai Storage, Shanghai</fullName>
            </value>
            <value>
                <fullName>Singapore FreePort, Singapore</fullName>
            </value>
            <value>
                <fullName>Success Building, Hong Kong</fullName>
            </value>
            <value>
                <fullName>Terrada S Building</fullName>
            </value>
            <value>
                <fullName>Tsing Yi, Hong Kong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Arpan-PersonalOrg/force-app/main/default/classes/TestAssetScannerControllerNew.cls
@isTest
public class TestAssetScannerControllerNew {
    static testMethod void testMeForBorrow(){
    	
    	Map<string, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Contact.getRecordTypeInfosByName();
    	Id conRT = rtMap.get('HT Staff - SG').getRecordTypeId(); 
    	Contact c = new contact();
	        c.RecordTypeId = conRT;
	        c.FirstName='Martin';
	        c.LastName='Lockwood';
	        c.Division__c='Singapore';
	        c.Gender_HT__c='Male';
	        c.ID_Type_HT__c='NRIC (Blue)';
	        c.ID_No_HT__c='S6860650H';
        insert c;
        
        Location__c L=new Location__c();
	        L.Name='Test Loaction';
	        L.Storage_Facility__c='Display Site';
	    insert L;  
	    
	    Asset__c A = new Asset__c();
        A.name='Test Machine';
        A.Brand__c='Tata Motors';
        A.Model__c='ABC12345';
        A.Type__c='Vehicle';
        A.Serial_No__c='000ABCF112';
        A.HT_Barcode_No__c='CR150414007';
        A.Location_User__c='HHGS';
        A.Asset_Type__c='Singapore';
        A.Location_New__c=null;
        A.Loaned_To__c = null;
        insert A;  
	    
	    PageReference editPage = Page.AssetScannerPage;
		Test.setCurrentPage(editPage);
		
		AssetScannerController ctrl = new AssetScannerController();
		List<selectOption> optionList = ctrl.getOptions();
		
		ctrl.selectedpickvalue = 'Borrow';
		ctrl.collection_string = A.HT_Barcode_No__c;
		ctrl.contactBarcode = c.ID_No_HT__c;
		ctrl.location = L.Name;
		ctrl.visibleSection = false;
		ctrl.messageFlag = false;
		ctrl.message = '';
		ctrl.message1 = '';
		ctrl.messageTitle = '';
		ctrl.messageFlagError = false;
		ctrl.messageFlagSuccess = false;
		
		ctrl.VisibleMethod();
		ctrl.updateSave();
		ctrl.Close();
    }
    
    static testMethod void testMeForReturn(){
    	
    	Map<string, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Contact.getRecordTypeInfosByName();
    	Id conRT = rtMap.get('HT Staff - SG').getRecordTypeId(); 
    	Contact c = new contact();
	        c.RecordTypeId = conRT;
	        c.FirstName='Martin';
	        c.LastName='Lockwood';
	        c.Division__c='Singapore';
	        c.Gender_HT__c='Male';
	        c.ID_Type_HT__c='NRIC (Blue)';
	        c.ID_No_HT__c='S6860650H';
        insert c;
        
        Location__c L=new Location__c();
	        L.Name='Test Loaction';
	        L.Storage_Facility__c='Display Site';
	    insert L;  
	    
	    Asset__c A = new Asset__c();
        A.name='Test Machine';
        A.Brand__c='Tata Motors';
        A.Model__c='ABC12345';
        A.Type__c='Vehicle';
        A.Serial_No__c='000ABCF112';
        A.HT_Barcode_No__c='CR150414007';
        A.Location_User__c='HHGS';
        A.Asset_Type__c='Singapore';
        A.Location_New__c=null;
        A.Loaned_To__c = null;
        insert A;  
	    
	    PageReference editPage = Page.AssetScannerPage;
		Test.setCurrentPage(editPage);
		
		AssetScannerController ctrl = new AssetScannerController();
		List<selectOption> optionList = ctrl.getOptions();
		
		ctrl.selectedpickvalue = 'Return';
		ctrl.collection_string = A.HT_Barcode_No__c;
		ctrl.contactBarcode = c.ID_No_HT__c;
		ctrl.location = L.Name;
		ctrl.visibleSection = false;
		ctrl.messageFlag = false;
		ctrl.message = '';
		ctrl.message1 = '';
		ctrl.messageTitle = '';
		ctrl.messageFlagError = false;
		ctrl.messageFlagSuccess = false;
		
		ctrl.VisibleMethod();
		ctrl.updateSave();
    }
    static testMethod void testMeErrorsForBorrow(){
    	
    	Map<string, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Contact.getRecordTypeInfosByName();
    	Id conRT = rtMap.get('HT Staff - SG').getRecordTypeId(); 
    	Contact c = new contact();
	        c.RecordTypeId = conRT;
	        c.FirstName='Martin';
	        c.LastName='Lockwood';
	        c.Division__c='Singapore';
	        c.Gender_HT__c='Male';
	        c.ID_Type_HT__c='NRIC (Blue)';
	        c.ID_No_HT__c='S6860650H';
        insert c;
        
        Location__c L=new Location__c();
	        L.Name='Test Loaction';
	        L.Storage_Facility__c='Display Site';
	    insert L;  
	    
	    Asset__c A = new Asset__c();
        A.name='Test Machine';
        A.Brand__c='Tata Motors';
        A.Model__c='ABC12345';
        A.Type__c='Vehicle';
        A.Serial_No__c='000ABCF112';
        A.HT_Barcode_No__c='CR150414007';
        A.Location_User__c='HHGS';
        A.Asset_Type__c='Singapore';
        A.Location_New__c=null;
        A.Loaned_To__c = null;
        insert A;  
	    
	    PageReference editPage = Page.AssetScannerPage;
		Test.setCurrentPage(editPage);
		
		AssetScannerController ctrl = new AssetScannerController();
		List<selectOption> optionList = ctrl.getOptions();
		
		ctrl.selectedpickvalue = 'Borrow';
		ctrl.collection_string = 'eknknk5,knknd4';
		ctrl.contactBarcode = 'Cknkne3';
		ctrl.location = L.Name;
		ctrl.visibleSection = false;
		ctrl.messageFlag = false;
		ctrl.message = '';
		ctrl.message1 = '';
		ctrl.messageTitle = '';
		ctrl.messageFlagError = false;
		ctrl.messageFlagSuccess = false;
		
		ctrl.VisibleMethod();
		ctrl.updateSave();
		ctrl.Close();
		
		ctrl.selectedpickvalue = 'Borrow';
		ctrl.collection_string = '';
		ctrl.contactBarcode = '';
		
		ctrl.updateSave();
				
    }
    static testMethod void testMeErrorsForReturn(){
    	
    	Map<string, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Contact.getRecordTypeInfosByName();
    	Id conRT = rtMap.get('HT Staff - SG').getRecordTypeId(); 
    	Contact c = new contact();
	        c.RecordTypeId = conRT;
	        c.FirstName='Martin';
	        c.LastName='Lockwood';
	        c.Division__c='Singapore';
	        c.Gender_HT__c='Male';
	        c.ID_Type_HT__c='NRIC (Blue)';
	        c.ID_No_HT__c='S6860650H';
        insert c;
        
        Location__c L=new Location__c();
	        L.Name='Test Loaction';
	        L.Storage_Facility__c='Display Site';
	    insert L;  
	    
	    Asset__c A = new Asset__c();
        A.name='Test Machine';
        A.Brand__c='Tata Motors';
        A.Model__c='ABC12345';
        A.Type__c='Vehicle';
        A.Serial_No__c='000ABCF112';
        A.HT_Barcode_No__c='CR150414007';
        A.Location_User__c='HHGS';
        A.Asset_Type__c='Singapore';
        A.Location_New__c=null;
        A.Loaned_To__c = c.Id;
        insert A;  
	    
	    PageReference editPage = Page.AssetScannerPage;
		Test.setCurrentPage(editPage);
		
		AssetScannerController ctrl = new AssetScannerController();
		List<selectOption> optionList = ctrl.getOptions();
		
		ctrl.selectedpickvalue = 'Return';
		ctrl.collection_string = 'eknknk5,knknd4';
		
		ctrl.location = L.Name;
		ctrl.visibleSection = false;
		ctrl.messageFlag = false;
		ctrl.message = '';
		ctrl.message1 = '';
		ctrl.messageTitle = '';
		ctrl.messageFlagError = false;
		ctrl.messageFlagSuccess = false;
		
		ctrl.VisibleMethod();
		ctrl.updateSave();
		ctrl.Close();
		
		ctrl.selectedpickvalue = 'Return';
		ctrl.collection_string = '';		
		
		ctrl.updateSave();
		
		ctrl.selectedpickvalue = 'Return';
		ctrl.collection_string = A.HT_Barcode_No__c+'knknds';
		
		ctrl.updateSave();
		
		ctrl.selectedpickvalue = 'Return';
		ctrl.collection_string = 'CR150414007';
		
		ctrl.updateSave();		
    }
}