2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/Crafting_Details__c.object-meta.xml
<CustomObject>
    <label>Crate Details</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Crating Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crate Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Artwork_Details__c.field-meta.xml
<CustomField>
    <fullName>Artwork_Details__c</fullName>
    <label>Artwork Details</label>
    <type>TextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Artwork_Type__c.field-meta.xml
<CustomField>
    <fullName>Artwork_Type__c</fullName>
    <label>Artwork Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2-D</fullName>
                <default>true</default>
                <label>2-D</label>
            </value>
            <value>
                <fullName>3-D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Base_Plate_Length_cm__c.field-meta.xml
<CustomField>
    <fullName>Base_Plate_Length_cm__c</fullName>
    <label>Base Plate Length (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Base_Plate_Width_cm__c.field-meta.xml
<CustomField>
    <fullName>Base_Plate_Width_cm__c</fullName>
    <description>Can you make this required only if the Base plate Checkbox is TRUE</description>
    <label>Base Plate Width (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Base_Support__c.field-meta.xml
<CustomField>
    <fullName>Base_Support__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Base Plate Support</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Breadth__c.field-meta.xml
<CustomField>
    <fullName>Breadth__c</fullName>
    <label>Breadth (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Breadth_in__c.field-meta.xml
<CustomField>
    <fullName>Breadth_in__c</fullName>
    <description>Breadth in Inches for Hong Kong</description>
    <label>Breadth (in)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Crate_No__c.field-meta.xml
<CustomField>
    <fullName>Crate_No__c</fullName>
    <label>Crate No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Crate_Type__c.field-meta.xml
<CustomField>
    <fullName>Crate_Type__c</fullName>
    <label>Crate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B Crate</fullName>
            </value>
            <value>
                <fullName>C Crate</fullName>
            </value>
            <value>
                <fullName>D Crate</fullName>
            </value>
            <value>
                <fullName>A-Frame</fullName>
            </value>
            <value>
                <fullName>T-Frame</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>No Crate. Supports Only</fullName>
                <label>No Crate. Supports Only. 不需要木箱</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Crating_Instruction__c.field-meta.xml
<CustomField>
    <fullName>Crating_Instruction__c</fullName>
    <label>Crating Instruction</label>
    <referenceTo>Crating_Instruction__c</referenceTo>
    <relationshipLabel>Crate Details</relationshipLabel>
    <relationshipName>Crafting_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Crating_Notes__c.field-meta.xml
<CustomField>
    <fullName>Crating_Notes__c</fullName>
    <label>Crating Notes</label>
    <type>TextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Foam__c.field-meta.xml
<CustomField>
    <fullName>Foam__c</fullName>
    <label>Foam</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>PE - 1 inch</fullName>
            </value>
            <value>
                <fullName>PE - 2 inch</fullName>
            </value>
            <value>
                <fullName>Grey - 1 inch</fullName>
            </value>
            <value>
                <fullName>Grey - 2 inch</fullName>
            </value>
            <value>
                <fullName>Styrofoam - 1 inch</fullName>
            </value>
            <value>
                <fullName>Styrofoam - 2 inch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Height_in__c.field-meta.xml
<CustomField>
    <fullName>Height_in__c</fullName>
    <description>Height in Inches for Hong Kong</description>
    <label>Height (in)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Length_in__c.field-meta.xml
<CustomField>
    <fullName>Length_in__c</fullName>
    <description>Length in Inches Fields for Hong Kong</description>
    <label>Length (in)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Crate Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Opening_Side__c.field-meta.xml
<CustomField>
    <fullName>Opening_Side__c</fullName>
    <label>Opening Side</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Broadside 宽面</fullName>
                <default>true</default>
                <label>Broadside 宽面</label>
            </value>
            <value>
                <fullName>Top 顶部</fullName>
            </value>
            <value>
                <fullName>Side+Top 宽面+顶</fullName>
            </value>
            <value>
                <fullName>All Sides 全面</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Triangle_Base_Width_cm__c.field-meta.xml
<CustomField>
    <fullName>Triangle_Base_Width_cm__c</fullName>
    <description>Can you make this required only if the Triangle Checkbox is TRUE</description>
    <label>Triangle Base Width (cm)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Triangle_Base_Width_in__c.field-meta.xml
<CustomField>
    <fullName>Triangle_Base_Width_in__c</fullName>
    <description>Triangle Base Width in Inches for Hong Kong</description>
    <label>Triangle Base Width (in)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crafting_Details__c/fields/Triangle_Supports__c.field-meta.xml
<CustomField>
    <fullName>Triangle_Supports__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triangle Supports</label>
    <type>Checkbox</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/Crating_Instruction__c.object-meta.xml
<CustomObject>
    <label>Crate Fabrication Instructions</label>
    <nameField>
        <displayFormat>CRI{YY}{MM}{DD}-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crate Fabrication Instructions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Artwork_Type__c.field-meta.xml
<CustomField>
    <fullName>Artwork_Type__c</fullName>
    <label>Artwork Type 艺术品类型</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Painting 画</fullName>
            </value>
            <value>
                <fullName>Sculpture  雕塑</fullName>
            </value>
            <value>
                <fullName>Print 印</fullName>
            </value>
            <value>
                <fullName>Photograph 照片</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Breadth__c.field-meta.xml
<CustomField>
    <fullName>Breadth__c</fullName>
    <label>Breadth 宽</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client 客户名称</label>
    <type>TextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Crate_Type__c.field-meta.xml
<CustomField>
    <fullName>Crate_Type__c</fullName>
    <label>Crate Type 箱子类型</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Date_of_Order__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Order__c</fullName>
    <label>Date of Order 订购曰期</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Foam__c.field-meta.xml
<CustomField>
    <fullName>Foam__c</fullName>
    <label>Foam</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>PE - 1 inch</fullName>
            </value>
            <value>
                <fullName>PE - 2 inch</fullName>
            </value>
            <value>
                <fullName>Grey  - 1 inch</fullName>
            </value>
            <value>
                <fullName>Grey  - 2 inch</fullName>
            </value>
            <value>
                <fullName>Styrofoam - 1 inch</fullName>
            </value>
            <value>
                <fullName>Styrofoam - 2 inch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height 高</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Job_Reference__c.field-meta.xml
<CustomField>
    <fullName>Job_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Reference   工作编号</label>
    <referenceTo>Job_Reference__c</referenceTo>
    <relationshipName>Crating_Instructions</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length 长</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <defaultValue>&quot;Use Plywood 用合板&quot;</defaultValue>
    <label>Notes 注释</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crating_Instruction__c/fields/Opening_Side__c.field-meta.xml
<CustomField>
    <fullName>Opening_Side__c</fullName>
    <label>Opening Side 开箱面</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Broadside 宽面</fullName>
                <default>true</default>
                <label>Broadside 宽面</label>
            </value>
            <value>
                <fullName>Top 顶部</fullName>
            </value>
            <value>
                <fullName>Side+Top 宽面+顶</fullName>
            </value>
            <value>
                <fullName>All Sides 全面</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Arpan-PersonalOrg/force-app/main/default/classes/PrintCratingInstructionController.cls
public with sharing class PrintCratingInstructionController {

    Crating_Instruction__c ciRec;
    public Crating_Instruction__c crateIns{get; set;}
    public list<Crafting_Details__c> craftingDetailsList {get;set;}

    public PrintCratingInstructionController(ApexPages.StandardController sc)
    {
        ciRec = (Crating_Instruction__c)sc.getRecord();
        craftingDetailsList = new list<Crafting_Details__c>();
        
        craftingDetailsList = [select CreatedDate, Triangle_Base_Width_cm__c,Triangle_Supports__c,Base_Plate_Width_cm__c,Base_Support__c,Crating_Notes__c,Base_Plate_Length_cm__c,Crate_No__c,Artwork_Details__c,Foam__c,Crate_Type__c, Artwork_Type__c, Opening_Side__c, Notes__c, Length__c, Breadth__c, 
                                    Height__c,Height_in__c,Length_in__c,Breadth_in__c,Triangle_Base_Width_in__c from Crafting_Details__c where Crating_Instruction__c =: ciRec.Id];
        
        crateIns = [Select Id,CreatedDate, Name, Client__c, Job_Reference__c,Job_Reference__r.Name, Date_of_Order__c, Required_Date__c, CreatedById,CreatedBy.Name,CS_Contact_No_New__c from Crating_Instruction__c where ID =:ciRec.Id];                            
    } 

}