2nd training/Community/Community/Community1/force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <description>Billing for jobs</description>
    <label>Billing</label>
    <nameField>
        <label>Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Billing__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/classes/billingOppProducts.cls
public class billingOppProducts {
	public List<OpportunityLineItem> oppLineItem;
	public Billing__c billing;
	
	public billingOppProducts(ApexPages.StandardController controller) {
        this.billing= (Billing__c)controller.getRecord();
    }
    
    public List<OpportunityLineItem> getOppLineItem() {
        Billing__c bill = [SELECT Id, Opportunity__r.Id FROM Billing__c where id = :billing.id];
        
        oppLineItem = [SELECT id, UnitPrice, TotalPrice, Quantity, PricebookEntry.Name, Opportunity.Id 
            FROM OpportunityLineItem WHERE Opportunity.Id = :bill.Opportunity__r.Id];
        if (oppLineItem == null) {
        	return null;
        }
        else {
        	return oppLineItem;
        }
    }//end of getOppLineItem

}