2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/Crate__c.object-meta.xml
<CustomObject>
    <description>Holds Collector Crate information</description>
    <label>Crate</label>
    <nameField>
        <label>Crate ID (barcode)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Collection_No__c.field-meta.xml
<CustomField>
    <fullName>Collection_No__c</fullName>
    <label>Collection No</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Date_In__c.field-meta.xml
<CustomField>
    <fullName>Date_In__c</fullName>
    <label>Date In</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Date_Out__c.field-meta.xml
<CustomField>
    <fullName>Date_Out__c</fullName>
    <label>Date Out</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Job_Reference__c.field-meta.xml
<CustomField>
    <fullName>Job_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Reference</label>
    <referenceTo>Job_Reference__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crate Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/Job_Reference__c.object-meta.xml
<CustomObject>
    <description>Stores the Job reference no</description>
    <label>Job Reference</label>
    <nameField>
        <label>Job Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <label>Attachment(s)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Job References</relationshipLabel>
    <relationshipName>Job_References</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/classes/TestCratetoArtworksSyncController.cls
@isTest
private class TestCratetoArtworksSyncController {

    static testMethod void myUnitTest() {
        
        Location__c Loc = new Location__c();
        Loc.Name = 'Location';
        insert Loc;
        
        opportunity o=new opportunity();
            o.StageName='Closed Won';
            o.name='Test Opp';
            o.CloseDate=System.TODAY();
            o.Estimated_Volume__c=30;
            o.Pack_Date_1__c=System.TODAY();
            o.Amount=50000;
            o.Quote_Number__c='Test Quote';
            o.OB_Job_Number__c='Test Job Number';
            o.attachment__c='Test Attachment';
            insert o;
            
		Job_Reference__c jobRef= new Job_Reference__c();
			jobRef.Name='Test Job Ref';
			jobRef.Opportunity__c=o.ID;
			insert jobRef;
        
        Crate__c c1 = new Crate__c();
        c1.Name = 'Barcode 1';
        c1.Job_Reference__c = jobRef.id;
        c1.Location__c = Loc.Id;
        c1.Date_In__c = system.today().addDays(-15);
        c1.Date_Out__c = system.today().addDays(20);
        c1.Collection_No__c = 'Test12345';
        insert c1;
              
		artApp__Artist__c artist = new artApp__Artist__c();
        artist.Name = 'Karthik';
        insert artist;
                
        artApp__Artwork__c Artwork = new artApp__Artwork__c();
        Artwork.Barcode_ID__c = 'Barcode 1';
        Artwork.artApp__Artist__c = artist.id;
        Artwork.Crate__c = c1.Id;
        insert Artwork;
        
        
        
        CratetoArtworksSyncController CASC = new CratetoArtworksSyncController(new ApexPages.StandardController(c1));
        
        CASC.jobReferenceNumber = false;
        CASC.location = false;
        CASC.dateIn = false;
        CASC.dateout = false;
        CASC.collector = false;
        
        CASC.syncArtworks();
        
        CASC.jobReferenceNumber = true;
        CASC.location = true;
        CASC.dateIn = true;
        CASC.dateout = true;
        CASC.collector = true;
                
        for(Integer i=0;i<CASC.artworksList.size();i++)
        	CASC.artworksList[i].selected = true;
        	
		CASC.syncArtworks();
        
    }
}