2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/Crate__c.object-meta.xml
<CustomObject>
    <description>Holds Collector Crate information</description>
    <label>Crate</label>
    <nameField>
        <label>Crate ID (barcode)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Collection_No__c.field-meta.xml
<CustomField>
    <fullName>Collection_No__c</fullName>
    <label>Collection No</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Date_In__c.field-meta.xml
<CustomField>
    <fullName>Date_In__c</fullName>
    <label>Date In</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Date_Out__c.field-meta.xml
<CustomField>
    <fullName>Date_Out__c</fullName>
    <label>Date Out</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Job_Reference__c.field-meta.xml
<CustomField>
    <fullName>Job_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Reference</label>
    <referenceTo>Job_Reference__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crate Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/Job_Reference__c.object-meta.xml
<CustomObject>
    <description>Stores the Job reference no</description>
    <label>Job Reference</label>
    <nameField>
        <label>Job Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/classes/createTrigger_Test.cls
@istest
public class createTrigger_Test {
    
    public static testmethod void method1(){
        Location__c Loc = new Location__c();
        Loc.Name = 'Location';
        insert Loc;
        
        Location__c Loc1 = new Location__c();
        Loc1.Name = 'Location';
        insert Loc1;
        
        
        
        Crate__c c1 = new Crate__c();
        c1.Name = 'Barcode 1';
      //  c1.Job_Reference__c = jobRef.id;
        c1.Location__c = Loc.Id;
        c1.Date_In__c = system.today().addDays(-15);
        c1.Date_Out__c = system.today().addDays(20);
        c1.Collection_No__c = 'Test12345';
        insert c1;
        
        artApp__Artist__c artist = new artApp__Artist__c();
        artist.Name = 'Karthik';
        insert artist;
        
        artApp__Artwork__c Artwork = new artApp__Artwork__c();
        Artwork.Barcode_ID__c = 'Barcode 1';
        Artwork.artApp__Artist__c = artist.id;
        Artwork.Crate__c = c1.Id;
        insert Artwork;
        
        c1.Location__c = Loc1.Id;
        update c1;
        
    }
}