2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/Crate__c.object-meta.xml
<CustomObject>
    <description>Holds Collector Crate information</description>
    <label>Crate</label>
    <nameField>
        <label>Crate ID (barcode)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/CBarcode_ID__c.field-meta.xml
<CustomField>
    <fullName>CBarcode_ID__c</fullName>
    <label>Crate Barcode ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Cycle_Count__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Count__c</fullName>
    <inlineHelpText>Sighting by Outer Pack</inlineHelpText>
    <label>Cycle Count</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Date_In__c.field-meta.xml
<CustomField>
    <fullName>Date_In__c</fullName>
    <label>Date In</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Date_Out__c.field-meta.xml
<CustomField>
    <fullName>Date_Out__c</fullName>
    <label>Date Out</label>
    <type>Date</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/IPPC_Stamp__c.field-meta.xml
<CustomField>
    <fullName>IPPC_Stamp__c</fullName>
    <inlineHelpText>Heat Treated or Fumigated</inlineHelpText>
    <label>IPPC Stamp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Job_Reference__c.field-meta.xml
<CustomField>
    <fullName>Job_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Reference</label>
    <referenceTo>Job_Reference__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crate Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/myCollector__c.field-meta.xml
<CustomField>
    <fullName>myCollector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collector</label>
    <referenceTo>artApp__Collector__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Is the crate empty or loaded?</description>
    <label>Empty or Loaded?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Empty</fullName>
            </value>
            <value>
                <fullName>Loaded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>unit of measurement</description>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>cm</fullName>
                <default>true</default>
                <label>cm</label>
            </value>
            <value>
                <fullName>inches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/With_Legs__c.field-meta.xml
<CustomField>
    <fullName>With_Legs__c</fullName>
    <label>With Legs?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/Job_Reference__c.object-meta.xml
<CustomObject>
    <description>Stores the Job reference no</description>
    <label>Job Reference</label>
    <nameField>
        <label>Job Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Job</fullName>
                <default>true</default>
                <label>New Job</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Arpan-PersonalOrg/force-app/main/default/classes/crateTriggerBatch.cls
global class crateTriggerBatch implements Database.Batchable<sObject>,Database.AllowsCallouts{
    public Set<Id> CrateIds = new Set<Id>();
    
    global crateTriggerBatch (List<Crate__c> crateList){
        system.debug('crateList>>'+crateList);        
        for(Crate__c crateObj : crateList){
            CrateIds.add(crateObj.Id);
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        system.debug('CrateIds>>>>'+CrateIds);
        //system.debug('?.>>>>'+Database.getQueryLocator([SELECT Id, Name,CurrencyIsoCode,RecordTypeId,myCollector__c,CBarcode_ID__c,Height__c,Length__c,UOM__c,Status__c,Width__c,Job_Reference__c,Date_In__c,Date_Out__c,With_Legs__c,Cycle_Count__c,IPPC_Stamp__c,IsActive__c from Crate__c WHERE Id IN : CrateIds]));
        return Database.getQueryLocator([SELECT Id,Keep_Id__c, SourceRFID__c,Name,CurrencyIsoCode,Location__c,RecordTypeId,myCollector__c,CBarcode_ID__c,Height__c,Length__c,UOM__c,Status__c,Width__c,Job_Reference__c,Date_In__c,Date_Out__c,With_Legs__c,Cycle_Count__c,IPPC_Stamp__c,IsActive__c from Crate__c WHERE Id IN : CrateIds]);
    }
    
    global void execute(Database.BatchableContext BC, List<Crate__c> crateList){
        system.debug('crateList>>>'+crateList);
        RFIDIntegrationUtility.RFIDCreateCrate(CrateList);
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
}