2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/Crate__c.object-meta.xml
<CustomObject>
    <description>Holds Collector Crate information</description>
    <label>Crate</label>
    <nameField>
        <label>Crate ID (barcode)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>artApp__Transaction__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/Crate_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Crate Line Item</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crate Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/fields/Crate__c.field-meta.xml
<CustomField>
    <fullName>Crate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crate</label>
    <referenceTo>Crate__c</referenceTo>
    <relationshipLabel>Crate Line Items</relationshipLabel>
    <relationshipName>Crate_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/fields/Crate_ID_barcode__c.field-meta.xml
<CustomField>
    <fullName>Crate_ID_barcode__c</fullName>
    <formula>Crate__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Crate ID (barcode)</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>artApp__Transaction__c</referenceTo>
    <relationshipLabel>Crate Line Items</relationshipLabel>
    <relationshipName>Crate_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

personal org/Arpan-PersonalOrg/force-app/main/default/classes/transactionTriggerBatch.cls
global class transactionTriggerBatch implements Database.Batchable<sObject>,Database.AllowsCallouts{
    public Set<Id> TransactionIds = new Set<Id>();
    
    global transactionTriggerBatch (List<artApp__Transaction__c> transactionList){
        system.debug('transactionList>>'+transactionList);        
        for(artApp__Transaction__c transactionObj : transactionList){
            TransactionIds.add(transactionObj.Id);
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        system.debug('TransactionIds>>>>'+TransactionIds);
        return Database.getQueryLocator([SELECT Id, Name,Crate__r.Id,Crate__r.Name from artApp__Transaction__c WHERE Id IN : TransactionIds]);
    }
    
    global void execute(Database.BatchableContext BC, List<artApp__Transaction__c> transactionList){
        system.debug('transactionList>>>'+transactionList);
        
        //List <Crate_Line_Item__c> crateLineList = [SELECT Id, Crate_ID_barcode__c,Transaction__c from Crate_Line_Item__c WHERE Transaction__c IN : TransactionIds];
        //List <artApp__Line_Item__c> artworkLineList = [SELECT Id, Barcode_ID__c,artApp__Transaction__c from artApp__Line_Item__c WHERE artApp__Transaction__c IN : TransactionIds];
        List <Crate_Line_Item__c> crateLineList = [SELECT Id, Crate_ID_barcode__c,Transaction__c,Crate__c from Crate_Line_Item__c WHERE Transaction__c IN : TransactionIds];
        List <artApp__Line_Item__c> artworkLineList = [SELECT Id, Barcode_ID__c,artApp__Transaction__c,artApp__Artwork__c from artApp__Line_Item__c WHERE artApp__Transaction__c IN : TransactionIds];
        
        Map<String,List<Crate_Line_Item__c>> crateLineMap = new Map<String,List<Crate_Line_Item__c>>();
        Map<String,List<artApp__Line_Item__c>> artworkLineMap = new Map<String,List<artApp__Line_Item__c>>();
        
        for(artApp__Transaction__c transObj : transactionList){
        	List <artApp__Line_Item__c> tempArtworkLineList = new List<artApp__Line_Item__c>();
            List <Crate_Line_Item__c> tempCrateLineList = new List<Crate_Line_Item__c>();
            
            for(Crate_Line_Item__c crateObj : crateLineList){
                if(transObj.Id == crateObj.Transaction__c){
                    tempCrateLineList.add(crateObj);
                }
            }
            crateLineMap.put(transObj.Id,tempCrateLineList);
            
            for(artApp__Line_Item__c artWorkObj : artworkLineList){
                if(transObj.Id == artWorkObj.artApp__Transaction__c){
                    tempArtworkLineList.add(artWorkObj);
                }
            }
            artworkLineMap.put(transObj.Id,tempArtworkLineList);
            
            //RFIDIntegrationUtility.RFIDCreateTransaction(transactionList);
            RFIDIntegrationUtility.RFIDCreateTransaction(transactionList,crateLineMap,artworkLineMap);
        }
        
        
        
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
}