2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/Crate__c.object-meta.xml
<CustomObject>
    <description>Holds Collector Crate information</description>
    <label>Crate</label>
    <nameField>
        <label>Crate ID (barcode)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/CBarcode_ID__c.field-meta.xml
<CustomField>
    <fullName>CBarcode_ID__c</fullName>
    <label>Crate Barcode ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/IPPC_Stamp__c.field-meta.xml
<CustomField>
    <fullName>IPPC_Stamp__c</fullName>
    <inlineHelpText>Heat Treated or Fumigated</inlineHelpText>
    <label>IPPC Stamp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <label>Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crate Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/myCollector__c.field-meta.xml
<CustomField>
    <fullName>myCollector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collector</label>
    <referenceTo>artApp__Collector__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Is the crate empty or loaded?</description>
    <label>Empty or Loaded?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Empty</fullName>
            </value>
            <value>
                <fullName>Loaded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>unit of measurement</description>
    <label>UOM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>cm</fullName>
                <default>true</default>
                <label>cm</label>
            </value>
            <value>
                <fullName>inches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <label>Width</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/With_Legs__c.field-meta.xml
<CustomField>
    <fullName>With_Legs__c</fullName>
    <label>With Legs?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/recordTypes/AMCrates.recordType-meta.xml
<RecordType>
    <fullName>AMCrates</fullName>
    <active>true</active>
    <label>AMCrates</label>
</RecordType>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Location__c/recordTypes/Artmove.recordType-meta.xml
<RecordType>
    <fullName>Artmove</fullName>
    <active>true</active>
    <label>Artmove</label>
</RecordType>

Arpan-PersonalOrg/force-app/main/default/classes/crateTriggerHandler_test.cls
@istest
public class crateTriggerHandler_test {
	static testmethod void dotest(){
        
        List<crate__c> crateIns_list = new List<crate__c>();
        List<crate__c> crateUp_list = new List<crate__c>();
        
        Id  locRTid = Schema.SObjectType.Location__c.getRecordTypeInfosByName().get('Artmove').getRecordTypeId();
        Location__c location1 = new Location__c();
        location1.Name = 'testlocation1';
        location1.CurrencyIsoCode = 'SGD';
        location1.RecordTypeId = locRTid;
        insert location1;
        
        
        Location__c location2 = new Location__c();
        location2.Name = 'testlocation2';
        location2.CurrencyIsoCode = 'SGD';
        location2.RecordTypeId = locRTid;
        insert location2;
        
        Id artColl_RTid = Schema.SObjectType.artApp__Collector__c.getRecordTypeInfosByName().get('Institutional').getRecordTypeId();
        artApp__Collector__c artColl1 = new artApp__Collector__c();
        artColl1.Name = 'Archduke Leopold William';
        artColl1.CurrencyIsoCode = 'SGD';
        artColl1.RecordTypeId = artColl_RTid;
        artColl1.Legal_nature_of_Entity__c = 'Company';
        artColl1.Invoice_Type__c = 'E-Invoice';
        insert artColl1 ;
        
        Id crate_RTid = Schema.SObjectType.Crate__c.getRecordTypeInfosByName().get('AMCrates').getRecordTypeId();
        Crate__c crate1 = new Crate__c();
        crate1.Name = 'CR230831003';
        crate1.CurrencyIsoCode = 'SGD';
        crate1.RecordTypeId = crate_RTid;
        crate1.myCollector__c = artColl1.id;
        crate1.CBarcode_ID__c = 'CR230831003';
        crate1.Height__c = 10;
        crate1.Length__c = 2;
        crate1.UOM__c = 'cm';
        crate1.Status__c = 'Loaded';
        crate1.Location__c = location1.id;
        crate1.Width__c = 5;       
        crate1.With_Legs__c = 'Yes';
        crate1.IPPC_Stamp__c = 'Yes';
        crate1.IsActive__c = true;
        crate1.SourceRFID__c = true;
        crateIns_list.add(crate1);
        insert crate1;
        
        
         crateTriggerHandler.upsertCrate(crateIns_list);
        
        crate1.Location__c =location2.id;
        update crate1;
    }
}