2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/Crate__c.object-meta.xml
<CustomObject>
    <description>Holds Collector Crate information</description>
    <label>Crate</label>
    <nameField>
        <label>Crate ID (barcode)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Job_Reference__c.field-meta.xml
<CustomField>
    <fullName>Job_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Reference</label>
    <referenceTo>Job_Reference__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/myCollector__c.field-meta.xml
<CustomField>
    <fullName>myCollector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collector</label>
    <referenceTo>artApp__Collector__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>artApp__Transaction__c</referenceTo>
    <relationshipLabel>Crates</relationshipLabel>
    <relationshipName>Crates</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/Crate_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Crate Line Item</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crate Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/fields/Crate__c.field-meta.xml
<CustomField>
    <fullName>Crate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crate</label>
    <referenceTo>Crate__c</referenceTo>
    <relationshipLabel>Crate Line Items</relationshipLabel>
    <relationshipName>Crate_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/fields/Job_Reference__c.field-meta.xml
<CustomField>
    <fullName>Job_Reference__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Job_Reference_ID__c ,  Job_Reference_Name__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Reference</label>
    <type>Text</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Crate_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>artApp__Transaction__c</referenceTo>
    <relationshipLabel>Crate Line Items</relationshipLabel>
    <relationshipName>Crate_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

2nd training/Community/Community/Community1/force-app/main/default/objects/Job_Reference__c/Job_Reference__c.object-meta.xml
<CustomObject>
    <description>Stores the Job reference no</description>
    <label>Job Reference</label>
    <nameField>
        <label>Job Ref No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Arpan-PersonalOrg/force-app/main/default/classes/CopyCrateToTransactionConExt.cls
public with sharing class CopyCrateToTransactionConExt extends DynamicListController {
    private List<CrateWrapper> crates;
    Map<Id, CrateWrapper> selectedCrateMap;
    public List<CrateWrapper> selectedCrates {get{return selectedCrateMap.values();}}

    public CopyCrateToTransactionConExt(ApexPages.StandardSetController con) {
        super('Select ' + getAllFields('Crate__c', gd )
            +' from Crate__c '
            +' where IsDeleted = false '
            +getWhere()
            ); 
        this.selectAll = true;
        this.pId =  ApexPages.CurrentPage().getParameters().get('id');
        if(this.pId != null){
            System.debug('object is '+ pId.getsobjecttype());
            this.objectLabel = pId.getsobjecttype().getDescribe().getLabel();
            this.objectName =  pId.getsobjecttype().getDescribe().getName();
        }
        this.t = new artApp__Line_Item__c();
        if(this.crates == null){this.crates = new List<CrateWrapper>();}
        if(selectedCrateMap == null){selectedCrateMap = new Map<Id, CrateWrapper>();}
    }
    
    private static String getWhere(){
        String whereClause = ' ';
        Id wId =  ApexPages.CurrentPage().getParameters().get('id');
        if(wId != null){
            System.debug('object is '+ wId.getsobjecttype());
            String oName = wId.getsobjecttype().getDescribe().getName();
            System.debug('oName is '+ oName);
            if(oName == 'Job_Reference__c'){
                whereClause += ' and Job_Reference__c = \'' + String.escapeSingleQuotes(wId) + '\'';
            }else if(oName == 'artApp__Collector__c'){
                whereClause += ' and myCollector__c = \'' + String.escapeSingleQuotes(wId) + '\'';
            }            
        }
        return whereClause;
    }
    
    public PageReference addSelected() {        
        for (CrateWrapper a :crates) {
            if (a.isSelected){
                selectedCrateMap.put(a.Crate.Id,a);
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,a.crate.name + ' added.'));
            }
        }
        return null;
    }
    
    public List<CrateWrapper> getCrates() {
        this.crates.clear();
        
        for (Crate__c a : (List<Crate__c>) getRecords()){
            if(!selectedCrateMap.containsKey(a.Id)){
                crates.add(new CrateWrapper(a));
            }
        }
        
        return crates;
    }
    
    public class CrateWrapper{
        public Boolean isSelected {get; set;}
        public Crate__c crate {get; private set;}
        
        public CrateWrapper(Crate__c a){
            crate = a;
            isSelected = true;    
        }  
    }
    
    public PageReference copyCrates() {
        System.debug('~~~selectedCrateMap '+ selectedCrateMap);
        System.debug('~~~this.t.artApp__Transaction__c '+ this.t.artApp__Transaction__c);
        List<Crate_Line_Item__c > lineItems = new List<Crate_Line_Item__c >();
        for (CrateWrapper a :selectedCrates ) {
            lineItems.add(new Crate_Line_Item__c(Transaction__c = this.t.artApp__Transaction__c, 
                                                 Crate__c = a.crate.Id
                                                ));   
        }
        System.debug('~~~lineItems '+ lineItems);
        Database.insert(lineItems);
        
        return cancel();
    }

}